### PR TITLE
fix: route notification BTW through side-turn contract

### LINKED ISSUE #2835: fix(coding-agent): repair post-#2832 BTW test contract regressions
## Regression

Dev CI run 29830446965 after merge #2832 fails because the new `/btw` controller contract was not propagated to broader tests.

Concrete failures:

1. `notifications-telegram-btw-e2e.test.ts` still expects the removed one-shot `<btw>` prompt instead of the multi-turn system-message contract.
2. `command-palette.test.ts` and `input-controller-skill-queue.test.ts` construct partial controller contexts without `hasActiveBtw`, causing `TypeError: this.ctx.hasActiveBtw is not a function` before unrelated slash-command assertions run.
3. The `/tmp owner_mismatch` failures in lifecycle tests are tracked separately by #2818 and are not part of this hotfix.

## Acceptance

- Update the minimum test fixtures/contracts needed for non-BTW controller users.
- Preserve fail-closed BTW routing and privacy behavior; do not weaken production checks merely to accommodate partial mocks.
- Update the Telegram BTW E2E assertion to the actual multi-turn provider request shape.
- Run the exact failing tests plus focused BTW/privacy tests and coding-agent checks.
- Open one PR to `dev`.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### PR DESCRIPTION
**Pull request by Yeachan-Heo**
## Summary
- preserve the raw Telegram `/btw` question through the notification seam
- route the request through AgentSession’s structured BTW side-turn path
- repair stale inactive-BTW InputController test fixtures without weakening production routing

Fixes #2835.

## Verification
- `bun --cwd=packages/coding-agent test test/notifications-telegram-btw-e2e.test.ts test/command-palette.test.ts test/input-controller-skill-queue.test.ts` — 32 passed
- nine focused BTW/privacy tests — 55 passed
- `bun --cwd=packages/coding-agent run check` — passed

`/tmp` owner-security and `notifications-lifecycle-control-runtime.test.ts` remain untouched; #2818 stays separate.

Reviewed head: `72d49d3dcae44f49e16112612de38b04fbe7f1ad`

— GJC

### CODE REVIEW

**Comment by Yeachan-Heo** [comment]
Exact-head adversarial review: `72d49d3dcae44f49e16112612de38b04fbe7f1ad` — CLEAR. No blockers found for raw-question preservation, structured BTW routing, host-owned deduplication/cancellation, fail-closed `hasActiveBtw` routing, or #2818 `/tmp` isolation.

— GJC

**Comment by Yeachan-Heo** [comment]
Merged after green exact-head CI and mergeability verification. Reviewed head: `72d49d3dcae44f49e16112612de38b04fbe7f1ad`; merge commit: `f9b0502f989d9d9ed1c51b1ee0b3197f9cbe2ad4`. #2818 `/tmp` owner-security scope remains untouched.

— GJC
