### PR TITLE
feat(notifications): add first-class provider settings

### LINKED ISSUE #3570: feat(tui): configure every notification provider inside Settings
## Problem

`Settings → Notifications` currently exposes notification providers unevenly: Telegram can be configured in the TUI, while Discord and Slack are effectively non-configurable from the settings UI. Users must leave the TUI and manipulate configuration through another surface.

## Required UX contract

Make every supported notification adapter configurable end-to-end inside the TUI settings flow, including Discord and Slack.

At minimum:

- list every supported notification provider in `Settings → Notifications`;
- provide provider-specific setup/edit screens for all required fields;
- show safe masked/fingerprinted secret state without echoing full tokens/webhooks;
- support enable/disable, edit, validation/test delivery, and recovery from invalid/incomplete configuration;
- explain missing prerequisites and actionable errors in the TUI rather than presenting a dead/non-configurable row;
- preserve the existing config schema, trust boundaries, and redaction rules unless a schema change is strictly required;
- cover keyboard navigation, cancellation/back behavior, persistence/reload, malformed config, and provider-specific validation with deterministic tests;
- update user-facing notification setup documentation.

This supersedes the incomplete UX closure of #2050 / #2088: moving notification setup into settings is not complete while supported Discord and Slack adapters cannot actually be configured there.

Owner directive source: Discord `#gajae-code-dev`, 2026-07-30 07:55 UTC.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### PR DESCRIPTION
**Pull request by Yeachan-Heo**
Closes #3570

## Summary
- adds first-class Telegram, Discord, and Slack settings with separate completeness, quarantine, durable desired intent, effective enablement, runtime readiness, and delivery outcomes
- preserves safe sibling providers, explicit keep/replace/remove secret actions, CAS-backed mutations, truthful post-commit degradation, and Telegram ownership isolation
- adds provider-aware CLI/TUI health and test flows, docs/schema/changelog updates, deterministic 108-entry terminal visual evidence, and generation-contract updates

## Verification
- 1,799 serialized notification tests passed across 63 files
- `bun run check:ts` passed
- `bun run check:rs` passed
- native build passed
- canonical workspace build passed
- generation/schema/rebrand/default-surface gates passed
- independent visual review CLEAR for 108 entries, manifest SHA-256 `91254dc64d2207bc7d8827482dec4e09f82e6a03d93d602816bddc3e4b3245e8`

### CODE REVIEW

**Comment by Yeachan-Heo** [comment]
Exact-head verification note for `8e806722393ca70bf86e50d0bb69a8aaec1b5766`: the affected bridge-client SDK package smoke failure reproduces independently on current `dev@85786e61d4d64757e5488cf478fb37af85c21481` (`getResidentCacheRootDir` missing) and on this head (`getAgentTerminalOwnerContext` missing). It is a pre-existing package-smoke defect outside issue #3570 notification ownership, not evidence of a notification regression. All issue-scoped exact-head checks remain separately required and are not waived.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Exact-head hold for `384dce79bf2f72c177606389319b108d930f747e`: Local public surfaces is inherited red from current `dev@7874b42ef39a0934e6a5043b923732e3cd837fe4`, where the merged #3629 tree has a stale generated docs index. This notification branch will not absorb the dedicated public-sync repair, and this head is not merge-eligible while the inherited red remains. All earlier exact-head review and CI authority is superseded. After the dedicated repair lands on dev, this same mutation branch will reconcile once and obtain fresh exact-head CI and hostile review.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Renewed current-dev hold: after public-sync repair #3630 merged, `dev` advanced to `bc11b36caa461b3dead9945ecebe1964a2f4feb7` and reintroduced the same stale generated docs-index failure. `bun run check:public-sync` reproduces directly on that dev tree. No new dedicated repair PR exists, so PR #3622 will not absorb the docs-index change or reconcile again until dev is repaired. Exact head `b0e1dc77e17f7ace2abed1de4f47d9118254e9a6` remains open and unmerged; its in-flight review/CI is non-terminal authority after dev advancement.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Successor exact head: `a628c851ab8bc72c8f2c6bd8bb4c5f36ef79efcd`\n\nRepair evidence: the package smoke reproduced the missing `getAgentTerminalOwnerContext` export from the packed `@gajae-code/agent-core/src/index.ts`. Contract review found this is internal terminal ownership metadata, not public SDK API, so no blind export was added. The smoke now packs and installs the matching agent-core tarball with an explicit dependency override and asserts installed package identity/version and realpath before probing the packed SDK.\n\nPassed locally: `bun run packages/coding-agent/scripts/build-sdk-package-smoke.ts`; 221 focused notification/provider/session/host tests; agent-core, bridge-client, and coding-agent type checks; coding-agent build; schema/generation tests. `check:sdk-closure` remains blocked by inherited AD-M-G07 `session.delete` fixture mismatch, unrelated to this two-file successor.\n\nLocal review signature: `gajae-exact-head-review-v1/a628c851ab8bc72c8f2c6bd8bb4c5f36ef79efcd/package-boundary-no-public-export`.

**Comment by Yeachan-Heo** [comment]
Canonical hostile exact-head review verdict\n\n- Exact head: `a628c851ab8bc72c8f2c6bd8bb4c5f36ef79efcd`\n- Verdict: `CLEAR`\n- Material findings: none\n- Canonical signature: `gajae-exact-head-review-v1:a628c851ab8bc72c8f2c6bd8bb4c5f36ef79efcd:CLEAR:no-material-findings`\n\nThe independent review confirmed the packed dependency-boundary repair adds no public export of the internal terminal-owner helper and does not introduce material regressions in the two-file successor.

**Comment by Yeachan-Heo** [comment]
Corrected exact-head hostile review\n\n- Exact head: `cf24023f4`\n- Verdict: `CLEAR`\n- Canonical payload: `{"findings":["installed agent-core realpath is confined to temporary packed install and rejected when it resolves to source workspace","installed agent-core package.json bytes are compared with extracted agent tarball package.json","same-version fallback is rejected by provenance and byte/identity checks","coding-agent blocks ./session/internal/* and does not export getAgentTerminalOwnerContext","SDK smoke probe and public-surface checks remain intact"],"head":"cf24023f4","schema":"gajae-exact-head-review-v1","verdict":"CLEAR"}`\n- SHA-256: `9774ab05b04dddae62ce6b1cf7f35d42ce01f017863b50866543259a510b5294`

**Comment by Yeachan-Heo** [comment]
Exact-head hostile review for PR #3622

Review boundary
- Repository: Yeachan-Heo/gajae-code
- Base: `7a535f377aee231750f7fc76302c5a2a0be1897f`
- Head: `cf24023f4d4b2474dd13d2a8007d4a5c151b4a0f`
- GitHub scope: 56 files, +5,257/-1,253
- No product files, commits, pushes, merges, or PRs were created by this review.

Terminal verdict: MERGE_READY

Evidence
- Focused notification/provider/session/host suite: `811 pass, 0 fail, 3,508 expect()` across 12 files. This covered `config.ts`, `notification-service.ts`, `notification-orchestration.ts`, `session-control.ts`, Telegram daemon paths, Discord/Slack live providers, chat-daemon worker wiring, and the Notifications settings editor/controller.
- Native dependency prerequisite: `bun --cwd=packages/natives run build` completed successfully; the generated addon was used only to make the local exact-head test environment runnable.
- Typecheck: `bun --cwd=packages/coding-agent run check:types` passed.
- Generated/schema checks: `bun run check:schemas` passed; `bun test scripts/telegram-daemon-generation-guard.test.ts scripts/generate-json-schemas.test.ts` passed with `47 pass, 0 fail`; the exact base/head generation guard reported `v29 required generation bump verified`.
- Packed release boundary: `bun run packages/coding-agent/scripts/build-sdk-package-smoke.ts` passed (`root: 657, sdk: 48`).
- Public synchronization: `bun run check:public-sync` passed.

Material review conclusions
- Provider configuration is global-only, provider-specific, CAS-backed, and preserves unrelated providers. Required-field completeness, malformed/blank/wrong-type quarantine, desired intent, global enablement, and effective enablement remain distinct.
- Secret replacement/keep/remove paths keep raw credentials out of safe UI drafts, daemon state, journals, status output, and diagnostics. Provider-specific sanitization covers Discord and both Slack credentials; Telegram diagnostics retain token-shaped redaction.
- Post-commit activation/deactivation reports durable-save versus runtime failure truthfully. Telegram retains its owner-identity preflight, blocked marker, CAS restore/retain path, root fencing, and dead-owner-only recovery.
- Discord and Slack daemon ownership uses identity/incarnation fencing, generation checks, readiness/transport health, durable effect journals, dedupe, replay/reconciliation, endpoint-generation binding, and shutdown draining. Discord interaction acknowledgement and Slack Socket Mode acknowledgement occur before long SDK dispatch while preserving durable claims.
- The Discord channel-private trust boundary is explicit in `docs/discord-onboarding.md`; Slack has an explicit authorized-user gate and remains outbound-only when unset. I found no exact-head wrong-recipient, credential-leak, duplicate-send, or stale-endpoint path that survived the focused review.
- SDK exports, generated schema/public-surface artifacts, package boundaries, and daemon generation manifests were independently checked. No internal terminal-owner helper was exposed through the packed SDK surface.

Expanded-suite classification
The broader notification glob also reached two failures in `packages/coding-agent/test/sdk-adapter-dispositions.test.ts`: `AD-M-G07` and `AD-A-G07` for `session.delete`. The smallest confirming command reproduced exactly those two failures. The test file is byte-unchanged across the reviewed base-to-head diff, and the relevant MCP/ACP/broker/operation-registry paths are also unchanged across that diff. The failure is therefore inherited adapter-parity/baseline noise, not a PR #3622 notification regression; it is excluded from the verdict evidence above rather than suppressed.

Automated/comment classification
- Comment `5138761667` from `chatgpt-codex-connector[bot]`: tooling/usage-limit noise.
- Owner comments tied to `8e806722`, `384dce79`, `b0e1dc77`, and `a628c851`: stale-head or inherited package/public-sync history; not used as current-head authority.
- Owner comment `5139962958` tied to `cf24023f4`: current-head package-boundary corroboration; the packed smoke was independently rerun here.
- Inline review comments currently reported: `0`.
- `gh pr checks` currently reports no checks for the branch, so this review does not claim remote CI green; the exact-head local evidence and generated/public checks above are the evidence used.

Review signature: `gajae-exact-head-review-v1/cf24023f4d4b2474dd13d2a8007d4a5c151b4a0f/notifications-review`

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
PR #3622 exact-head rebase reconciliation

Rebased and pushed the actual PR head branch `feat/issue-3570-notifications-settings`.

- Previous exact head: `cf24023f4d4b2474dd13d2a8007d4a5c151b4a0f`
- New exact head: `4ed9aa6aaf3a73161cb01aa37fdffe0e55d6e9d1`
- Verified base: `origin/dev` at `58c1b16127ef6585743d0dd9b308b368713b3794`
- Push: force-with-lease succeeded; PR remains open and was not merged.

Conflict resolution scope

- Reconciled notification generation contracts and tests with current-dev lifecycle authority.
- Preserved #3596 upstream lifecycle fixes, including Telegram generation 40 and current Discord/Slack generation authority.
- Preserved PR #3622 first-class Telegram, Discord, and Slack provider settings, provider intent, CAS/configuration behavior, and provider-aware runtime paths.
- Regenerated `packages/coding-agent/src/internal-urls/docs-index.generated.ts` and `scripts/telegram-daemon-generation-manifest.json` after resolution.
- No unresolved index entries, conflict markers, or unrelated source changes remain.

Latest exact-head validations

- Focused notification/provider/session/host suite: `849 pass, 0 fail` across 12 files (`3,689 expect()` calls).
- Notification red-team/e2e suite: `44 pass, 0 fail` across 5 files (`10,010 expect()` calls).
- Generation/schema tests: `48 pass, 0 fail` across 2 files (`404 expect()` calls).
- Current-tree generation guard: passed.
- Schema synchronization: passed.
- Typechecks: `packages/coding-agent`, `packages/agent`, `packages/bridge-client`, and `packages/natives` passed.
- Native addon build completed and the local linux-x64-modern artifact was present.
- Packed SDK smoke: passed (`root: 657`, `sdk: 48`).
- Public synchronization: passed.
- Rebase invariant: `origin/dev` is an ancestor of the new head; working tree is clean.

Review-gate evidence

The review evidence contract was repaired after these exact receipt findings:

- `qualityGate executorQa.artifactRefs must be a non-empty object array`
- `qualityGate executorQa.surfaceEvidence must be a non-empty object array`

The rerun then reached this exact remaining gate finding:

- `COMPUTER_REDTEAM_CASE_MISSING: qualityGate executorQa.adversarialCases must include kill-switch-bypass`

This is a conservative Ultragoal runtime computer-suite requirement triggered by the changed settings-schema path, not a source defect identified by the rebase or notification validations. No unrelated computer-suite investigation was performed, and the finding is not being suppressed.

Fresh hostile review

Required: yes. The prior hostile review was bound to `cf24023f4`; the rebase and subsequent force-push changed the exact head. The local leader-owned red-team/e2e results above do not replace a fresh independent hostile review for `4ed9aa6a`.

Review signature: `gajae-exact-head-rebase-v1:4ed9aa6aaf3a73161cb01aa37fdffe0e55d6e9d1:conflict-repair-validation`

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
PR #3622 exact-head generation-guard repair

Repaired and pushed the actual PR branch after CI rejected head `4ed9aa6aaf3a73161cb01aa37fdffe0e55d6e9d1`.

- New exact head: `660aa2d3c`
- Base: `origin/dev` `58c1b16127ef6585743d0dd9b308b368713b3794`
- Push: force-with-lease succeeded to `feat/issue-3570-notifications-settings`
- PR remains open and was not merged.

Root cause from the failed Telegram daemon generation-guard job

1. CI reported: `telegram-daemon-generation-guard: guard policy change requires a strictly higher GUARD_CONTRACT_VERSION`.
2. After correcting the guard policy version, the exact local base/head run exposed the second required invariant: `telegram-daemon-generation-guard: protected Telegram lifecycle change requires a strictly higher DAEMON_GENERATION` for the provider-settings protected declarations.

Minimal repair

- Bumped `GUARD_CONTRACT_VERSION` from 34 to 35.
- Advanced Telegram `DAEMON_GENERATION` from 40 to 41.
- Advanced chat generations from Discord 23 to 24 and Slack 22 to 23.
- Regenerated the generation manifest and updated the Telegram generation assertion to 41.
- No unrelated source or computer-suite changes were made.

Local repair evidence

- `bun scripts/telegram-daemon-generation-guard.ts --validate-current-tree`: passed.
- Exact base/head guard run: `telegram-daemon-generation-guard: v35 required generation bump verified`.
- CI authority-input replay with the exact base/head SHAs: passed.
- `bun test scripts/telegram-daemon-generation-guard.test.ts packages/coding-agent/test/notifications-telegram-daemon.test.ts`: `556 pass, 0 fail, 2,373 expect()`.
- Working tree is clean with no unresolved index entries or conflict markers.

The prior guard failure was a real generation-contract defect in the rebased branch, not an infrastructure failure. Fresh exact-head review remains required for `660aa2d3c`; the prior hostile review was bound to the earlier head.

Repair signature: `gajae-exact-head-rebase-v1:660aa2d3c:telegram-generation-guard-repair`

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
CI follow-up for PR #3622

The Telegram daemon generation guard now passes on exact head `660aa2d3cc5400a94b9c02359232ad5d7f2098b9` against base `58c1b16127ef6585743d0dd9b308b368713b3794`.

- Job: `Telegram daemon generation guard`
- Result: passed
- Guard output: `telegram-daemon-generation-guard: v35 required generation bump verified`
- Local authority-input replay and 556-test generation/Telegram suite also pass.

The remaining Dev CI workflow shards are still queued/in progress; this update claims only the repaired guard, not full workflow completion. The PR remains open and unmerged.

Repair signature: `gajae-exact-head-rebase-v1:660aa2d3c:telegram-generation-guard-ci-pass`

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
PR #3622 CI status update for repaired head `660aa2d3c`

The Telegram daemon generation guard is green on the repaired head (`v35 required generation bump verified`). The remaining required CI failure is unrelated to the generation-guard repair:

- Jobs: `Affected path validation / check:@gajae-code/coding-agent` and `Affected path validation / root-check`
- Failing command: `bun run check:tools`
- Exact failure: Biome reports one formatting error in `packages/coding-agent/scripts/build-sdk-package-smoke.ts`, in the `tar` extraction block and the installed-package name/version conditional around lines 123-144.
- Local reproduction: `bun run check:tools` fails identically with `Checked 3290 files ... Found 1 error`.
- No formatter or unrelated source repair was applied in this lane; the generation guard, manifest, DAEMON_GENERATION/CHAT_DAEMON_GENERATIONS, and local guard tests remain green.

The PR remains open and unmerged. This comment records the exact CI blocker rather than suppressing it.

Repair signature: `gajae-exact-head-rebase-v1:660aa2d3c:ci-formatting-blocker`

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
PR #3622 CI formatter repair

Applied the requested formatting-only correction and pushed a fresh exact head.

- Previous head: `660aa2d3cc5400a94b9c02359232ad5d7f2098b9`
- New exact head: `1afc5789e`
- Push: force-with-lease succeeded to `feat/issue-3570-notifications-settings`
- PR remains open and unmerged.

Repair scope

- Only `packages/coding-agent/scripts/build-sdk-package-smoke.ts` changed.
- Biome formatted the tar extraction block and installed-package name/version conditional.
- No runtime behavior or unrelated product code was changed.

Validation

- `bun run check:tools`: passed (`Checked 3290 files ... No fixes applied`).
- Current-tree generation validation: passed.
- Exact base/head generation guard: `telegram-daemon-generation-guard: v35 required generation bump verified`.
- Guard plus Telegram generation tests: `556 pass, 0 fail, 2,373 expect()`.

The push triggered a fresh CI run for the new head. No merge was performed.

Repair signature: `gajae-exact-head-rebase-v1:1afc5789e:formatter-only-ci-repair`

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
MERGE_READY — fresh hostile exact-head review for `1afc5789ea4ec5c85327ac8b12220fd8e3f99ee7`\n\nReview scope\n- Exact PR head and PR metadata verified: head matches `1afc5789e`, PR #3622 remains open, base is `dev`, mergeability is clean.\n- Rebase/repair diff reviewed against current `origin/dev` (`58c1b16127ef6585743d0dd9b308b368713b3794`): the post-review delta is the formatter-only `build-sdk-package-smoke.ts` commit; no semantic notification or generation change is present in that delta.\n- Generation authority attacked across the Telegram/Discord/Slack inventory, declaration digests, native authority digests, and manifest closure. Exact guard invocation passed: `telegram-daemon-generation-guard: v35 required generation bump verified`. Manifest contract is v35 with all three provider families and 263 declaration digests / 7 native-authority digests.\n- Notifications contract review covered provider-settings admission, daemon generation ownership/reclaim authority, transition fencing, config/host wiring, and the added Discord/Slack/Telegram regression coverage. Focused review tests passed: 204 passed, 0 failed, 1,212 expects.\n- Generated schema closure passed: `bun scripts/generate-json-schemas.ts --check`.\n- REST check-runs for the exact head are terminal: 0 failed, 0 pending. Required CI lanes including generation guard, native build, notification settings test, SDK shard, CLI smoke, state gates, and public surfaces are green; only platform-inapplicable checks are skipped.\n\nKnown non-blocking baseline note\n- The local tracked-tree Telegram baseline generator reports two omitted commands (`notifications-telegram-daemon-staging-temp-leak.test.ts` and `notifications-topic-settle-fence-epoch.test.ts`). Both tests already exist on `origin/dev`, the baseline manifest is unchanged by this PR, and neither omission is introduced by the PR #3622 diff. This is recorded as inherited base debt, not a branch blocker.\n\nNo edit or merge was performed.\n\nReview signature: `gajae-exact-head-hostile-review-v1:1afc5789e:MERGE_READY`\n\n—\n*[repo owner\x27s gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
POST-MERGE DOGFOOD COMPLETE\n\n- PR #3622 verified merged through GitHub REST at dev commit `0cc1536db0705154c5f0454e0b62694f29427a7a`.\n- Created and verified dedicated detached worktree: `/tmp/pr-3622-postmerge-dogfood`, exact `HEAD=0cc1536db0705154c5f0454e0b62694f29427a7a`.\n- Initial `bun run build` attempt reached the build pipeline but exited 1 because the fresh worktree had no installed `tailwindcss/index.css`.\n- `bun install --frozen-lockfile` could not complete in this environment: the `node-pty` install script hit the host Node.js `node-gyp` prerequisite error `Cannot find module 'nopt'`.\n- Installed the locked dependency tree with `bun install --frozen-lockfile --ignore-scripts`, then reran the exact gate.\n- Final `bun run build`: PASS / exit 0. Native addon build, Tailwind, React client, embedded client generation, native embedding, and `dist/gjc` compilation all completed.\n- Final dogfood worktree is clean; generated embedded output was reset by the build.\n- No release action performed.\n\nPost-merge signature: `gajae-post-merge-dogfood-v1:0cc1536db:PASS`\n\n—\n*[repo owner\x27s gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Signed: Yeachan-Heo / fresh-session batch lane

OWNER LANE RETIRED — terminal evidence reconciled.

- #3622 is merged and closed at dev commit `0cc1536db0705154c5f0454e0b62694f29427a7a`.
- Existing post-merge dogfood receipt `gajae-post-merge-dogfood-v1:0cc1536db:PASS` is verified: final detached worktree build passed after the documented `--ignore-scripts` dependency recovery.
- Hosted post-merge checks at `0cc1536db` are terminal: 39 total, 34 success, 5 policy skips, 0 failures, 0 non-terminal.
- Notifications/settings ownership is complete and remains retired under the existing owner. No mutation lane is reopened; no follow-up issue or merge action is created.
