### ISSUE TITLE
Post-merge dogfood: coding-agent typecheck and compiled gjc native loading fail

### ISSUE THREAD

**Issue by Yeachan-Heo** [Yeachan-Heo/gajae-code#264]
## Summary

Post-merge dogfood on current `dev` (`7e73da03ac7ba229d938c61d9a0792e5c9551e99`) found two real surface failures:

1. `@gajae-code/coding-agent` typecheck fails after the telemetry warning addition from #255.
2. The compiled binary `packages/coding-agent/dist/gjc` fails immediately because it cannot load/extract the `pi_natives` native addon, while the source CLI path works.

## Repro

After fast-forwarding canonical dev:

```bash
git -C /home/bellman/Workspace/gajae-code pull --ff-only origin dev
bun run build
bun --cwd=packages/coding-agent run check:types
./packages/coding-agent/dist/gjc --version
```

### 1. Typecheck failure

```text
$ tsgo -p tsconfig.json --noEmit
src/sdk.ts(54,34): error TS2345: Argument of type '{ code: "full_content_capture_env_active"; message: string; }' is not assignable to parameter of type 'AgentTelemetryWarning'.
  Types of property 'code' are incompatible.
    Type '"full_content_capture_env_active"' is not assignable to type '"content_serializer_failed" | ... | "resolve_attributes_failed"'.
```

The source enum/interface in `packages/agent/src/telemetry.ts` includes `full_content_capture_env_active`, but the coding-agent typecheck path still sees a stale/narrower `AgentTelemetryWarning` type.

### 2. Compiled binary native addon failure

Source CLI works:

```bash
bun packages/coding-agent/src/cli.ts --version
# gjc/0.3.0
bun packages/coding-agent/src/cli.ts harness --help
# ok
```

Compiled binary fails:

```bash
./packages/coding-agent/dist/gjc --version
```

Error excerpt:

```text
[Uncaught Exception] Error: Failed to load pi_natives native addon for linux-x64 (modern).

Tried:
- /home/bellman/.gjc/natives/0.3.0/pi_natives.linux-x64-modern.node
- /home/bellman/.local/bin/pi_natives.linux-x64-modern.node
- /$bunfs/native/pi_natives.linux-x64-modern.node
- /home/bellman/Workspace/gajae-code/packages/coding-agent/dist/pi_natives.linux-x64-modern.node
...
```

But local build output has natives under:

```text
packages/natives/native/pi_natives.linux-x64-modern.node
packages/natives/native/pi_natives.linux-x64-baseline.node
```

## Expected

- `bun --cwd=packages/coding-agent run check:types` passes on current dev.
- The compiled `dist/gjc` binary can start and run `--version` / `--help` after `bun run build`, or the build should place/embed/stage native addons so the compiled binary can find them.

## Impact

This is a direct dogfood failure of the real shipped/developer surface after all PRs were merged green. CI/focused tests did not catch it.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Fixed by PR #265 and merged into `dev` at `b5bab79`.

Post-merge status:
- PR #265 merged.
- Dogfood failures addressed: coding-agent type boundary + compiled `dist/gjc` native addon staging.
- Merge-gate evidence: PR CI passed and GJC red-team review returned APPROVE.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*
