### PR TITLE
Fix issue #264 dogfood native and telemetry failures

### LINKED ISSUE #264: Post-merge dogfood: coding-agent typecheck and compiled gjc native loading fail
## Summary

Post-merge dogfood on current `dev` (`7e73da03ac7ba229d938c61d9a0792e5c9551e99`) found two real surface failures:

1. `@gajae-code/coding-agent` typecheck fails after the telemetry warning addition from #255.
2. The compiled binary `packages/coding-agent/dist/gjc` fails immediately because it cannot load/extract the `pi_natives` native addon, while the source CLI path works.

## Repro

After fast-forwarding canonical dev:

```bash
git -C /home/bellman/Workspace/gajae-code pull --ff-only origin dev
bun run build
bun --cwd=packages/coding-agent run check:types
./packages/coding-agent/dist/gjc --version
```

### 1. Typecheck failure

```text
$ tsgo -p tsconfig.json --noEmit
src/sdk.ts(54,34): error TS2345: Argument of type '{ code: "full_content_capture_env_active"; message: string; }' is not assignable to parameter of type 'AgentTelemetryWarning'.
  Types of property 'code' are incompatible.
    Type '"full_content_capture_env_active"' is not assignable to type '"content_serializer_failed" | ... | "resolve_attributes_failed"'.
```

The source enum/interface in `packages/agent/src/telemetry.ts` includes `full_content_capture_env_active`, but the coding-agent typecheck path still sees a stale/narrower `AgentTelemetryWarning` type.

### 2. Compiled binary native addon failure

Source CLI works:

```bash
bun packages/coding-agent/src/cli.ts --version
# gjc/0.3.0
bun packages/coding-agent/src/cli.ts harness --help
# ok
```

Compiled binary fails:

```bash
./packages/coding-agent/dist/gjc --version
```

Error excerpt:

```text
[Uncaught Exception] Error: Failed to load pi_natives native addon for linux-x64 (modern).

Tried:
- /home/bellman/.gjc/natives/0.3.0/pi_natives.linux-x64-modern.node
- /home/bellman/.local/bin/pi_natives.linux-x64-modern.node
- /$bunfs/native/pi_natives.linux-x64-modern.node
- /home/bellman/Workspace/gajae-code/packages/coding-agent/dist/pi_natives.linux-x64-modern.node
...
```

But local build output has natives under:

```text
packages/natives/native/pi_natives.linux-x64-modern.node
packages/natives/native/pi_natives.linux-x64-baseline.node
```

## Expected

- `bun --cwd=packages/coding-agent run check:types` passes on current dev.
- The compiled `dist/gjc` binary can start and run `--version` / `--help` after `bun run build`, or the build should place/embed/stage native addons so the compiled binary can find them.

## Impact

This is a direct dogfood failure of the real shipped/developer surface after all PRs were merged green. CI/focused tests did not catch it.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### PR DESCRIPTION
**Pull request by Yeachan-Heo**
Fixes #264.

## Summary
- export `AgentTelemetryWarningCode` and type the coding-agent full-content warning against `AgentTelemetryWarning` so package-boundary checks accept `full_content_capture_env_active`
- stage workspace-built `pi_natives.*.node` files next to `packages/coding-agent/dist/gjc` after the dev compile build
- add regression coverage for the warning-code type boundary and dev build native staging contract

## Verification
- `bun test packages/coding-agent/test/issue-264-dogfood.test.ts packages/coding-agent/test/telemetry-full-capture-warning.test.ts packages/natives/test/issue-823-repro.test.ts`
- `bun --cwd=packages/coding-agent run check:types`
- `bun run build`
- `./packages/coding-agent/dist/gjc --version`
- `./packages/coding-agent/dist/gjc --help`

### CODE REVIEW

**Comment by Yeachan-Heo** [comment]
Red-team review verdict: APPROVE.

Evidence:
- Diff inspected against `dev`.
- CI passed: `Affected path validation`, `gjc-state-gates`.
- GJC review verified: `bun --cwd=packages/coding-agent run check:types`, issue #264 dogfood test, `bun run build`, compiled `./packages/coding-agent/dist/gjc --version`, `--help`, `--smoke-test`, and native loader regression tests.
- No blockers found.

GitHub cannot record an approval review from this account because the PR is treated as own/owner-authored; this comment is the review evidence for merge gate.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*
