### PR TITLE
fix(natives): bound Windows AVX2 fallback probe

### LINKED ISSUE #4781: [Windows] Bound AVX2 PowerShell fallback timeout in required gate
## Summary

The required Windows job fails on the current `dev` tree and on PR #4772 head `1750770d7b682dd4aa19da94b65604573b2141e0`, in the live PowerShell 5.1 fallback test for the AVX2 probe. This is outside PR #4772's trusted-home/NSS delta and blocks merge until the owning Windows/native lane fixes and reruns the gate.

## Exact evidence

- PR head: `1750770d7b682dd4aa19da94b65604573b2141e0`
- Current dev base: `a34cbd700b56b9c663daef700e5edd14cbd20470`
- Failed job: [Windows dev:doctor + session-path regression](https://github.com/Yeachan-Heo/gajae-code/actions/runs/32412496468/job/96566096394)
- Runner: Windows Server 2025, image `windows-2025-vs2026` version `20260818.207.1`
- Test command: `bun test ./packages/natives/test/windows-avx2-probe.windows.test.ts`

The preceding live tests passed:

```text
(pass) ... in-process kernel32 probe returns a decisive boolean ... [2.21ms]
(pass) ... default detection chain spawns no subprocess ... [0.78ms]
```

The forced fallback then failed:

```text
(fail) windows AVX2 probe live execution (#4652) > PowerShell 5.1-compatible fallback P/Invoke works when invoked on a real Windows host [5029.78ms]
  ^ this test timed out after 5000ms.
killed 1 dangling process

2 pass
1 fail
Ran 3 tests across 1 file. [5.09s]
##[error]Process completed with exit code 1.
```

No assertion mismatch, PowerShell stdout, or PowerShell stderr was emitted before the synchronous fallback hung; the runner killed the dangling process at the Bun 5-second test deadline.

## Diagnosis

`packages/natives/native/loader-state.js` still calls `childProcess.spawnSync("powershell.exe", ..., { windowsHide: true })` without a timeout. The test forces `detectWin32Avx2Support(() => undefined)`, so it exercises that fallback directly. The failure is therefore a recurring Windows PowerShell/native-probe timeout/environment failure in the repository gate, not a trusted-home change in PR #4772.

PR #4772 has no diff in the AVX2 loader, live test, or Windows CI path relative to `dev`. PR #4780 is the unrelated `errno_name` Windows test-compilation fix; it does not implement the AVX2 probe fix.

## Ownership

Please take this in the Windows/native AVX2 lane associated with closed #4652/#4654. The fix must preserve hidden subprocess behavior, remain compatible with stock Windows PowerShell 5.1, bound or otherwise prevent a wedged fallback from exceeding the test/runtime budget, and rerun the required Windows gate with full stdout/stderr evidence.

Until that owning fix is merged and the exact PR head is rerun green, #4772 must not merge.

### PR DESCRIPTION
**Pull request by Yeachan-Heo**
## What

Bound the Windows AVX2 PowerShell fallback in production and add timeout/termination regression coverage.

## Why

Fixes #4781. Unchanged PR #4772 head repeatedly exceeded Bun's 5,000 ms Windows test deadline on a newer runner image, and Bun killed one dangling PowerShell process. The exact failure is recorded at https://github.com/Yeachan-Heo/gajae-code/actions/runs/32414712250/job/96573338334.

- `child_process.spawnSync` and the build-host `Bun.spawnSync` path use a 4,000 ms timeout, `SIGKILL`, hidden-window execution, and a 4 KiB output cap.
- Timeout, spawn-error, nonzero-exit, and non-decisive output paths fail closed to the baseline variant.
- Diagnostics are shape-only (`timeout`, `spawn_error`, `nonzero_exit`, `non_decisive_output`); raw command, environment, stdout, stderr, and error messages are not emitted.
- The stock Windows PowerShell 5.1-compatible P/Invoke command remains unchanged.
- After this merges, PR #4772 must rebase and regenerate its digest/review rather than rerun its unchanged head.

## Testing

- `bun test packages/natives/test/windows-avx2-probe.test.ts scripts/host-detect.test.ts --timeout 10000` — 18 pass
- `bun --cwd=packages/natives test --timeout 10000` — 148 pass, 55 skip
- `bun --cwd=packages/natives run check` — pass
- `bun run check:tools` — pass (two pre-existing informational lint notices outside this diff)
- `bun test scripts/ci-dev-affected.test.ts scripts/dev-ci-guard-topology.test.ts --timeout 30000` — 104 pass
- Required Windows live execution — `windows-dev-doctor` in this PR
- No release or version bump

## Risk classification

- [x] `low-risk` — ordinary fix/maintenance; the repository owner may use the explicit `merge-self-approved` solo verdict (no independent human review; the verdict name itself records this) with a risk-record comment bound to the exact head.
- [ ] `regression-risk` — fix with material regression risk; requires one assigned independent domain reviewer whose authenticated exact-head `APPROVED` review the gate verifies (`extra:independent:<login>`; the token alone never suffices).
- [ ] `high-risk` — large refactor, feature, or materially high-risk change (security/auth/install/remove/public API/destructive lifecycle/architecture); requires one assigned independent domain reviewer with an authenticated exact-head `APPROVED` review (`extra:independent:<login>`).

## GJC verdict

```text
gajae.pr-review-verdict.v1 merge-self-approved sha256:51947d01bf77add1f544665bfd9feba56bb935f47a9810dcdcf322e50664d8f9 reviewer:human reviewer-id:Yeachan-Heo evidence:bun test packages/natives/test/windows-avx2-probe.test.ts scripts/host-detect.test.ts --timeout 10000
```

---

- [x] Target branch is `dev`
- [x] `bun check` passes for the affected package/tooling checks
- [x] Tested locally
- [x] CHANGELOG updated (if user-facing)
- [x] Verdict above matches the exact PR head, not an earlier commit
- [x] Risk classification above matches the actual review path taken

### CODE REVIEW

**Comment by Yeachan-Heo** [comment]
gajae.pr-self-review.v1 verdict:merge-self-approved base:343067ab8f9ab75f427e275f411ca1ed57814ea0 head:4a8785ca00dd6e305e539989de6e401cc9345a86 sha256:51947d01bf77add1f544665bfd9feba56bb935f47a9810dcdcf322e50664d8f9 reviewer-id:Yeachan-Heo risk:low-risk extra:none evidence:bun test packages/natives/test/windows-avx2-probe.test.ts scripts/host-detect.test.ts --timeout 10000; bun --cwd=packages/natives test --timeout 10000
self-review-signature: sha256:3002e087e15469d9f224babf32adb4e4cc276b18ee6fdcd4a6f3737c5078d4ba
Signed-off-by: gaebal-gajae (clawdbot) 🦞

**Comment by Yeachan-Heo** [comment]
Terminal exact-head evidence for PR #4783

- Base: `343067ab8f9ab75f427e275f411ca1ed57814ea0`
- Head: `4a8785ca00dd6e305e539989de6e401cc9345a86`
- Canonical diff SHA-256: `51947d01bf77add1f544665bfd9feba56bb935f47a9810dcdcf322e50664d8f9`
- Exact-head contract validator: `PR contract valid: merge-self-approved 51947d01bf77add1f544665bfd9feba56bb935f47a9810dcdcf322e50664d8f9`
- Current exact-head PR contract run: https://github.com/Yeachan-Heo/gajae-code/actions/runs/32417064572 — passed.
- Substantive Dev CI run: https://github.com/Yeachan-Heo/gajae-code/actions/runs/32416500005 — affected-path/native cargo, native probe tests, Windows live probe test, host-detect test, state gates, tooling/public-surface checks, and virtual integration passed. Its obsolete bootstrap failure predates the repaired PR body; the current bootstrap run passed at https://github.com/Yeachan-Heo/gajae-code/actions/runs/32417064158.
- Deterministic local probe regression tests: 18 passed, 0 failed across `packages/natives/test/windows-avx2-probe.test.ts` and `scripts/host-detect.test.ts`.
- Timeout/error behavior is bounded at 4,000 ms with `SIGKILL`, `windowsHide`, 4 KiB output cap, safe baseline fallback, shape-only diagnostics, and no raw command/environment/stdout/stderr emission. The Windows live lane passed the fallback bounded-return test.

Exact signed self-review/risk record:

gajae.pr-self-review.v1 verdict:merge-self-approved base:343067ab8f9ab75f427e275f411ca1ed57814ea0 head:4a8785ca00dd6e305e539989de6e401cc9345a86 sha256:51947d01bf77add1f544665bfd9feba56bb935f47a9810dcdcf322e50664d8f9 reviewer-id:Yeachan-Heo risk:low-risk extra:none evidence:bun test packages/natives/test/windows-avx2-probe.test.ts scripts/host-detect.test.ts --timeout 10000; bun --cwd=packages/natives test --timeout 10000
self-review-signature: sha256:3002e087e15469d9f224babf32adb4e4cc276b18ee6fdcd4a6f3737c5078d4ba
Signed-off-by: gaebal-gajae (clawdbot) 🦞
