### ISSUE TITLE
fix(coding-agent): repair post-#2832 BTW test contract regressions

### ISSUE THREAD

**Issue by Yeachan-Heo** [Yeachan-Heo/gajae-code#2835]
## Regression

Dev CI run 29830446965 after merge #2832 fails because the new `/btw` controller contract was not propagated to broader tests.

Concrete failures:

1. `notifications-telegram-btw-e2e.test.ts` still expects the removed one-shot `<btw>` prompt instead of the multi-turn system-message contract.
2. `command-palette.test.ts` and `input-controller-skill-queue.test.ts` construct partial controller contexts without `hasActiveBtw`, causing `TypeError: this.ctx.hasActiveBtw is not a function` before unrelated slash-command assertions run.
3. The `/tmp owner_mismatch` failures in lifecycle tests are tracked separately by #2818 and are not part of this hotfix.

## Acceptance

- Update the minimum test fixtures/contracts needed for non-BTW controller users.
- Preserve fail-closed BTW routing and privacy behavior; do not weaken production checks merely to accommodate partial mocks.
- Update the Telegram BTW E2E assertion to the actual multi-turn provider request shape.
- Run the exact failing tests plus focused BTW/privacy tests and coding-agent checks.
- Open one PR to `dev`.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Resolved by #2838, merged to `dev` as f9b0502f989d9d9ed1c51b1ee0b3197f9cbe2ad4. The exact failing BTW contract tests and focused privacy matrix passed before merge.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*
