### ISSUE TITLE
fix(session): reconcile before-agent-start ordering after default-model admission redesign

### ISSUE THREAD

**Issue by Yeachan-Heo** [Yeachan-Heo/gajae-code#4519]
## Exact regression

Dev CI run `31736419453` at `96e8f23ea808844ea27a4dc59468bc9f111dc4fc`, shard-2 job `94572361145` fails `packages/coding-agent/test/agent-session-before-agent-start-attribution.test.ts` after merged PR #4496 / commit `e4f4281ac80dc2d7deb0ae31cbbe4e5570760308` changed `setDefaultModelSelection` admission ordering.

Exact failures:

1. `:224` — `orders an accepted prompt before a later default selection through provider start`: expected selection credential probe not to overtake active prompt preflight, but it now does (`Expected false, Received true`).
2. `orders an accepted default selection before later prompt preflight`: `DefaultModelSelectionRecoveryError` after durable selection.
3. `:336` — `disposal drains an active selection`: queued prompt rejects with same-session `AgentBusyError` during dispose and escapes as unhandled error.

The same file was unchanged after #4496; the production diff explicitly moved credential probe and `waitForIdle` outside the selection admission. #4496 focused suites did not include this cross-contract test. This is distinct from #4518 auth-storage fixture drift and #4501 ACP cleanup classification.

## Acceptance

- Reconcile the canonical contract between prompt preflight attribution, default-model selection, and dispose.
- Preserve #4496's auto-compaction deadlock fix; do not put `waitForIdle` back under a lease that blocks continuation prompt admission.
- Preserve fail-fast reentrancy and missing-credential semantics where compatible with causal admission ordering.
- Credential probing/durable mutation must not violate accepted prompt ordering or mutate a successor session.
- Default-selection-first then prompt, prompt-first then selection, same-session reentrancy, abort, and dispose all settle deterministically without unhandled rejection or recovery error.
- Run the exact failing file, #4496 default-model-selection suite, auto-compaction continuation suite, SDK host wiring, and exact shard-2.
- One focused PR to current `dev`, independent exact-head adversarial review, full CI, merge, closure, and postmerge Dev CI.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Active implementation ownership is resumed in the dedicated #4519 lane. The preserved patch currently touches only `agent-session.ts`, the default-model-selection regression suite, and the auto-compaction continuation suite.

The lane was based at `96e8f23ea808844ea27a4dc59468bc9f111dc4fc`; exact current `dev` is `59ac14e7bd5af05d6ce38dfa80b0b2b2100051e3`. No PR exists yet. The dirty patch is being preserved and reconciled onto current dev before focused verification. Required closure remains: original before-agent-start failures, #4496 default-model suite, auto-compaction continuation, SDK host wiring, exact shard 2, package checks/types, one focused PR, independent exact-head review, terminal CI, dev merge, issue closure, and postmerge verification. No timeout/sleep inflation or expectation weakening is allowed.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Signed evidence — issue #4519 owner lane

- Original regression evidence read exactly: Dev CI run `31736419453`, shard-2 job `94572361145`, head `96e8f23ea808844ea27a4dc59468bc9f111dc4fc`.
- Focused PR: #4524.
- Exact current PR head: `fc08b48884b05a4f29804a37044f970f1808641a`.
- Exact current base: `38f3b4077c870e41d061f8f2aa7f5c873a30e25f`.
- Ancestry proof: merge-base equals exact base.
- Focused suites: 181 pass, 1 existing skip, 0 fail.
- coding-agent check/types: pass.
- isolated production SDK host: pass.
- exact shard-2 reached only independent `login-preset-recommendation.test.ts` auth fixture failure (`authStorage.listCredentialInventory is not a function`), outside this issue's explicitly separated #4518 contract.

The implementation preserves #4496: `waitForIdle` remains outside session admission and inherited continuation prompt admission bypasses only the external selection fence. Same-session hook reentrancy remains fail-fast. Prompt-first, selection-first, cancellation/successor, pending continuation, and disposal contracts settle deterministically.

Signed: Bellman / issue-4519 owner

**Comment by probepark** [comment]
Reproduction on the current `dev` tip, from PR-review triage of #4523 (this was the residual shard-2 red after #4523 merged, and it is not caused by #4523).

`dev` @ `4906d0e29` ("Merge pull request #4523"), detached worktree, fresh `bun install --frozen-lockfile`, rebuilt natives:

```
$ bun test packages/coding-agent/test/agent-session-before-agent-start-attribution.test.ts
(fail) AgentSession before_agent_start attribution fallback > orders an accepted prompt before a later default selection through provider start [17.90ms]
(fail) AgentSession before_agent_start attribution fallback > orders an accepted default selection before later prompt preflight [73.13ms]
(fail) AgentSession before_agent_start attribution fallback > disposal drains an active selection [15.78ms]
 6 pass
 3 fail
```

Same 6/3 split on `65130ce03` (#4523 head) and on `099ca7ec1` (its base), so the regression predates #4523 entirely.

Failure signature for the third one:

```
AgentBusyError: Agent session admission is busy due to same-session reentrancy.
 code: "busy"
      at #sessionAdmissionBusyError (packages/coding-agent/src/session/agent-session.ts:2548:24)
      at #withSessionAdmission (packages/coding-agent/src/session/agent-session.ts:2641:68)
      at async <anonymous> (packages/coding-agent/test/agent-session-before-agent-start-attribution.test.ts:336:9)
```

So `disposal drains an active selection` is hitting the reentrancy fast-fail in `#withSessionAdmission` instead of draining, which matches the acceptance bullet about dispose and reentrancy needing to be reconciled rather than treated independently.

CI evidence for the same three tests on a PR run: job `94656764773` (`Affected path validation / test:@gajae-code/coding-agent:shard-2-of-8`), run `31763710478`.

Worth noting for anyone triaging red shards: shard-2's failure list is currently dominated by this file, so it will keep marking unrelated PRs red until #4519 lands.

**Comment by Yeachan-Heo** [comment]
Terminal evidence for issue #4519:

- PR #4524 merged to `dev` at merge commit `34f5db331b484726c447f6ab026f35c8b391a879` from exact independently approved head `3baf82e3ac7ce0143b80e51e934ffd128cb7a982` over base `4906d0e29c18d137d15c19af11a2bb0864f017ad`.
- Merge reachability verified: the reviewed head is an ancestor of canonical `origin/dev`.
- Independent authenticated exact-head approval: probepark review `4933522086` — https://github.com/Yeachan-Heo/gajae-code/pull/4524#pullrequestreview-4933522086
- Authoritative normal pull-request CI run `31767310776`: terminal success, including bootstrap, native build, focused attribution/default-selection/auto-compaction tests, coding-agent check/types, evidence producer, and aggregate.
- Authoritative postmerge Dev CI run `31768516300` at exact merge commit: terminal success with no failed jobs.
- Postmerge shard 2 job `94670381939`: success — https://github.com/Yeachan-Heo/gajae-code/actions/runs/31768516300/job/94670381939
- Postmerge evidence producer job `94672516322`: success — https://github.com/Yeachan-Heo/gajae-code/actions/runs/31768516300/job/94672516322
- Postmerge aggregate job `94672547841`: success — https://github.com/Yeachan-Heo/gajae-code/actions/runs/31768516300/job/94672547841
- Canonical merged worktree verification: attribution/default-selection/auto-compaction suites 79 pass + 1 existing skip, SDK host wiring 104/104 in isolated execution, coding-agent check/types pass.
- Canonical merged local build: `bun run build` completed successfully, including native addon and compiled `dist/gjc`.
- Worktree is clean at canonical dev; no postmerge source push was made because no authoritative postmerge regression exists.

The original run `31736419453`, shard-2 job `94572361145`, and the later current-dev reproductions are resolved. Prompt-first and selection-first causal ordering, same-session fail-fast reentrancy, inherited continuation admission without holding selection across `waitForIdle`, successor/cancellation behavior, and deterministic disposal settlement are all covered and green.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Issue #4519 was reopened for a required postmerge fix-forward after the terminal Ultragoal architecture gate proved a concrete ownerless-continuation deadlock not exercised by the merged CI matrix.

- merged PR #4524 remains valid for its original three shard-2 regressions and postmerge Dev CI run `31768516300` was terminal green
- terminal architect proof: an ownerless auto-compaction continuation scheduled first can reach prompt admission after selection reserves its fence; selection then waits tracked continuation through `waitForIdle`, while continuation waits the selection fence
- focused fix-forward PR: #4540 — https://github.com/Yeachan-Heo/gajae-code/pull/4540
- exact current base/head: `f0453b6ab179d0802226721ac2c333113cd5a6ee` / `b0205ea727fce986d835f477f2c5a856714139e8`
- exact digest: `8680be026128ee3e451c117328227ed5823b4cde021bdbc26db8ebbd554654c3`
- deterministic regressions added for ownerless continuation-before-selection and SDK queued ingress; no sleeps or timeout changes
- focused suites: 81 pass, 1 existing skip, 0 fail; isolated SDK host 104/104; coding-agent check/types pass

This fix-forward was opened because the active Ultragoal gate is fail-closed; terminal completion cannot claim CLEAR while a proven original-contract deadlock remains.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
## Disposition recovery — implementation owner confirmed

- The sole open implementation owner is PR #4540 (`fix/issue-4519-selection-order`), in dedicated worktree `/home/bellman/Workspace/gajae-code-pr-4540-selection-order`. This disposition worktree is read-only and has not modified its source.
- Current exact base/head: `9d2a2d2f2d8f074333bba92fe1fc4d6902f5b2df` / `5670ca11f18f0451c5ce7b638a39d191f4a5594a`; head is not yet reachable from `origin/dev`.
- Contract coverage is present in the final head’s deterministic attribution, auto-compaction, manual-retry, SDK host-runtime, router-authority, and notification regressions. The affected-path CI run `31835476693` passed its relevant test, coding-agent check, native-build, and shard work.
- Exact blocker: the current PR verdict remains `needs-human`. PR-contract runs `31835476693` (bootstrap) and `31835877324` (review event) correctly fail closed: the exact-head verdict line has not been updated to `merge-approved` by an independent authenticated reviewer. GitHub’s aggregate `APPROVED` is therefore insufficient because it includes stale approvals.
- Merge/close dependency: obtain a fresh independent exact-head approval and merge-approved verdict for `5670ca11…`, then obtain terminal successful PR CI, verify the merge commit on `origin/dev` with postmerge product evidence, and only then close #4519.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Resolved and merged into `dev` via #4540.

- reviewed PR head: `33dc4d61e8b8dd1c578900b04fa1e5c544c70271`
- merge commit: `96e718a2b0f2a46cad4876bf922886966c6fd0e3`
- merged at: `2026-08-15T02:42:17Z`
- exact-head approval, PR contract, affected validation, evidence producer, and virtual integration were terminal green.

Closing as fixed.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*
