### PR TITLE
fix(session): preserve causal model selection order

### LINKED ISSUE #4519: fix(session): reconcile before-agent-start ordering after default-model admission redesign
## Exact regression

Dev CI run `31736419453` at `96e8f23ea808844ea27a4dc59468bc9f111dc4fc`, shard-2 job `94572361145` fails `packages/coding-agent/test/agent-session-before-agent-start-attribution.test.ts` after merged PR #4496 / commit `e4f4281ac80dc2d7deb0ae31cbbe4e5570760308` changed `setDefaultModelSelection` admission ordering.

Exact failures:

1. `:224` — `orders an accepted prompt before a later default selection through provider start`: expected selection credential probe not to overtake active prompt preflight, but it now does (`Expected false, Received true`).
2. `orders an accepted default selection before later prompt preflight`: `DefaultModelSelectionRecoveryError` after durable selection.
3. `:336` — `disposal drains an active selection`: queued prompt rejects with same-session `AgentBusyError` during dispose and escapes as unhandled error.

The same file was unchanged after #4496; the production diff explicitly moved credential probe and `waitForIdle` outside the selection admission. #4496 focused suites did not include this cross-contract test. This is distinct from #4518 auth-storage fixture drift and #4501 ACP cleanup classification.

## Acceptance

- Reconcile the canonical contract between prompt preflight attribution, default-model selection, and dispose.
- Preserve #4496's auto-compaction deadlock fix; do not put `waitForIdle` back under a lease that blocks continuation prompt admission.
- Preserve fail-fast reentrancy and missing-credential semantics where compatible with causal admission ordering.
- Credential probing/durable mutation must not violate accepted prompt ordering or mutate a successor session.
- Default-selection-first then prompt, prompt-first then selection, same-session reentrancy, abort, and dispose all settle deterministically without unhandled rejection or recovery error.
- Run the exact failing file, #4496 default-model-selection suite, auto-compaction continuation suite, SDK host wiring, and exact shard-2.
- One focused PR to current `dev`, independent exact-head adversarial review, full CI, merge, closure, and postmerge Dev CI.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### PR DESCRIPTION
**Pull request by Yeachan-Heo**
## Summary

- Reserve default-model selection ordering before credential probing so an already accepted prompt cannot be overtaken.
- Fence later external prompt preflight through durable default selection while allowing inherited post-prompt continuations to bypass only the external fence.
- Preserve fail-fast same-session reentrancy and deterministically drain accepted selection work during disposal while rejecting queued prompts without unhandled rejections.
- Add deterministic coverage for prompt-first, selection-first, same-session selection/prompt reentrancy, cancellation, successor sessions, queued successors, pending auto-compaction continuation, and disposal.

## Exact provenance

- Issue: #4519
- Original failing Dev CI: run `31736419453`, shard-2 job `94572361145`, head `96e8f23ea808844ea27a4dc59468bc9f111dc4fc`
- Current-dev failing CI: run `31764983841`, exact dev `4906d0e29c18d137d15c19af11a2bb0864f017ad`
- PR base: `4906d0e29c18d137d15c19af11a2bb0864f017ad`
- PR head: `3baf82e3ac7ce0143b80e51e934ffd128cb7a982`
- Exact diff digest: `6e56942f84ef6de4fb89e55ecb90439b699faf0ca629a76bbb029200aa587b49`

## Failure-set delta

Before this PR, `agent-session-before-agent-start-attribution.test.ts` failed because selection credential probing overtook accepted prompt preflight, later prompt preflight overtook an accepted selection and caused `DefaultModelSelectionRecoveryError`, and disposal leaked a same-session `AgentBusyError`. On this exact head all 11 attribution tests pass, including the original three failures plus deterministic reentrant-prompt and queued-successor adversarial cases. The exact eight-way shard 2 now passes all 174 files after #4518 landed.

## Validation

- `bun test packages/coding-agent/test/agent-session-before-agent-start-attribution.test.ts` — 11 pass, 0 fail
- `bun test packages/coding-agent/test/agent-session-default-model-selection.test.ts` — 45 pass, 0 fail
- `bun test packages/coding-agent/test/agent-session-auto-compaction-continue.test.ts` — 23 pass, 1 existing skip, 0 fail
- `bun test packages/coding-agent/test/sdk-host-wiring.test.ts` — 104 pass, 0 fail when run in isolation
- `bun scripts/run-bun-test-files.ts --root=packages/coding-agent --shard=2/8 --timeout=30000 --file-timeout=300000 --concurrency=1` — 174/174 files passed
- `bun --cwd=packages/coding-agent run check` — pass

Fixes #4519

gajae.pr-review-verdict.v1 merge-approved sha256:6e56942f84ef6de4fb89e55ecb90439b699faf0ca629a76bbb029200aa587b49 reviewer:human reviewer-id:probepark evidence:https://github.com/Yeachan-Heo/gajae-code/pull/4524#pullrequestreview-4933522086

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### CODE REVIEW

**Comment by Yeachan-Heo** [comment]
Signed evidence — issue #4519 owner lane

- Original regression evidence read exactly: Dev CI run `31736419453`, shard-2 job `94572361145`, head `96e8f23ea808844ea27a4dc59468bc9f111dc4fc`.
- Focused PR: #4524.
- Exact current PR head: `fc08b48884b05a4f29804a37044f970f1808641a`.
- Exact current base: `38f3b4077c870e41d061f8f2aa7f5c873a30e25f`.
- Ancestry proof: merge-base equals exact base.
- Focused suites: 181 pass, 1 existing skip, 0 fail.
- coding-agent check/types: pass.
- isolated production SDK host: pass.
- exact shard-2 reached only independent `login-preset-recommendation.test.ts` auth fixture failure (`authStorage.listCredentialInventory is not a function`), outside this issue's explicitly separated #4518 contract.

The implementation preserves #4496: `waitForIdle` remains outside session admission and inherited continuation prompt admission bypasses only the external selection fence. Same-session hook reentrancy remains fail-fast. Prompt-first, selection-first, cancellation/successor, pending continuation, and disposal contracts settle deterministically.

Signed: Bellman / issue-4519 owner

**Comment by Yeachan-Heo** [comment]
Dependency evidence for superseded head `fc08b48884b05a4f29804a37044f970f1808641a`, Dev CI run `31742971196`:

- linked clawhip/ts-build job `94593397853`: SUCCESS; alert attribution was incorrect.
- shard 3 job `94593397681`: failures are `acp-builtins.test.ts` provider usage/account expectations and `sdk-operation-inventory.test.ts` generated matrix drift, owned by #4518 / PR #4523. This PR does not duplicate or absorb that auth/inventory repair.
- shard 7 job `94593397744`: cascading `sdk-host-wiring.test.ts` durable prompt/skill cancellation failures, owned by #4522. This PR does not duplicate or absorb that implementation.
- shard 4, notifications-live-stream, session-manager-resident-cache, and ts-build were green.

Independent review of that head found two issue-local ordering defects. Fix-forward head `1ec407b3be` now checks same-session prompt reentrancy before the selection fence and deterministically fences a later streaming successor behind an earlier accepted selection. Focused current-worktree verification: 183 pass, 1 existing skip, 0 fail; coding-agent check/types pass.

This current head will be rebased onto exact dev after PR #4523 and #4522 land, then receives fresh full CI and exact-head review.

Signed: Bellman / issue-4519 owner

— *[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Authoritative current-dev regression evidence for #4519:

- exact dev head/base: `38f3b4077c870e41d061f8f2aa7f5c873a30e25f`
- failed push Dev CI run: `31742182235`
- exact shard-2 job: `94592074663`
- #4519-owned failures in `agent-session-before-agent-start-attribution.test.ts`:
  1. `orders an accepted prompt before a later default selection through provider start`
  2. `orders an accepted default selection before later prompt preflight`
  3. `disposal drains an active selection`
- login-preset failures in that shard remain separately owned by #4518 and are not included here.

Current PR head `1ec407b3be980c5914b2e1b59a3af31cced3bf25` deterministically covers all three failures plus independent review's same-session prompt reentrancy and later queued-successor findings. Fresh-process verification on this exact worktree/head:

- `bun test packages/coding-agent/test/agent-session-before-agent-start-attribution.test.ts`: 11 pass, 0 fail
- `bun test packages/coding-agent/test/agent-session-default-model-selection.test.ts`: 45 pass, 0 fail
- `bun test packages/coding-agent/test/agent-session-auto-compaction-continue.test.ts`: 23 pass, 1 existing skip, 0 fail
- `bun test packages/coding-agent/test/sdk-host-wiring.test.ts`: 104 pass, 0 fail
- combined relevant suite: 183 pass, 1 existing skip, 0 fail
- `bun --cwd=packages/coding-agent run check`: pass

No expectations were weakened, no timeout/sleep was added, and `waitForIdle` remains outside selection admission so inherited post-prompt continuation can obtain prompt admission.

Signed: Bellman / issue-4519 owner

— *[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Current full-census dependency status for PR #4524:

- exact #4524 head: `1ec407b3be980c5914b2e1b59a3af31cced3bf25`
- exact recorded base/current dev: `38f3b4077c870e41d061f8f2aa7f5c873a30e25f`
- latest full review-event run: `31745131277` — not terminal merge-ready
- shard 2/3 composition remains red on external #4518 `authStorage` inventory/generated-operation regressions owned by **PR #4523**, which is currently open and unmerged
- durable skill-acceptance cancellation dependency remains owned by **issue #4522** in its dedicated current owner lane; #4522 has no PR yet

This sole #4519 owner lane remains active. It will not rerun the known-stale composition or copy either dependency. After PR #4523 and issue #4522's eventual PR land on dev, #4524 will be rebased/reconstructed on exact current dev, then receive fresh exact shards/full CI, independent exact-head approval, canonical verdict, merge, issue closure, and postmerge Dev CI verification. Any remaining #4524-owned failure will be fixed causally in this branch.

Signed: Bellman / issue-4519 owner

— *[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Cross-PR exact downstream evidence for #4519 ownership:

- downstream PR #4521 review-event run `31749018651` ended terminal cancelled after primary shard failures
- exact shard-2 job `94612651696` ran on a branch without PR #4524 and reproduced all three current-dev #4519 failures in `agent-session-before-agent-start-attribution.test.ts`:
  1. prompt-first ordering: selection credential probe overtook accepted prompt preflight (`Expected: false`, `Received: true`) and emitted an unhandled same-session `AgentBusyError`
  2. selection-first ordering: `DefaultModelSelectionRecoveryError` after durable selection
  3. disposal: queued prompt escaped with same-session `AgentBusyError`
- the same job's `login-preset-recommendation.test.ts` failure (missing `authStorage.listCredentialInventory`) is strictly #4518 / PR #4523 and is not part of #4519
- downstream shard 8 passed

PR #4524 exact remote/worktree equality was reconfirmed at `1ec407b3be980c5914b2e1b59a3af31cced3bf25`; base/current dev remains `38f3b4077c870e41d061f8f2aa7f5c873a30e25f`. Current issue-only proof without source churn:

- exact admission/selection/continuation suites: 79 pass, 1 existing skip, 0 fail
- exact shard-2 equivalent reaches only the external #4518 `login-preset-recommendation.test.ts` failure; the #4519 attribution file passes on this head
- SDK host cancellation failures observed in mixed runs remain separately owned by issue #4522 and are not absorbed here

Signed: Bellman / issue-4519 owner

— *[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
**Exact-head CI classification — no #4524-owned failure remains in run `31758733081`.**

- PR head: `166877d7e619a89e35a9007054438bff79455f4c`
- Base/current dev: `099ca7ec19654b2863f0a113ed569c8e7e96b9f5`
- `ts-build` and shards 1, 4, 5, 6, 7, 8: success
- shard 2: seven `login-preset-recommendation` failures, all `authStorage.listCredentialInventory is not a function`
- shard 3: `agent_session:setCredentialAuto` inventory seam plus ACP `/usage` authStorage fixture failures

Those shard 2/3 failures are the exact bounded #4518 cluster already owned by PR #4523; they are not introduced by #4524. The #4518 owner has been resumed to rebase #4523 from stale base `38f3b4077c` onto current dev, push fresh exact-head evidence, merge #4523, and then hand back for a clean #4524 rebase/rerun. Do not duplicate the auth fixture patch into this branch. #4524 remains dependency-owned, not terminal or merge-ready.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Dependency evidence: current-base run 31758733081, shard-3 job 94641991570 fails on the exact #4518 ACP AuthStorage fixture and SDK operation inventory drift. PR #4523 has been rebased onto current dev and exact head `ad570c8dc04318d45dd5cc9d1e52e983b4b168f9` passes focused suites plus shard 3 (174/174). Do not absorb these fixes into #4524; rebase #4524 after #4523 lands.\n\n

**Comment by Yeachan-Heo** [comment]
Direct blocker coordination from external maintainer PR #4512: #4524's current-base full run fails the #4518 auth/account inventory families owned by PR #4523, while #4523's exact-head approved run `31763710478` fails only this PR's #4519 shard-2 family (`94656764773`). The diffs are disjoint. Please coordinate a policy-compliant stacked/batch landing so one current-base candidate contains both fixes and reaches terminal full-census green; after the first lands, rebase/terminalize the remaining PR. #4512 will not absorb sibling code or bypass checks and remains blocked on this composition plus #4522.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
PR #4523 / issue #4518 has merged into dev as `4906d0e29c18d137d15c19af11a2bb0864f017ad`. Rebase this branch onto current dev and rerun; do not retain duplicate ACP auth fixture or SDK inventory work from the pre-merge base.

**Comment by Yeachan-Heo** [comment]
PR #4523 dependency landed and #4524 was immediately reconstructed on exact current dev.

- merged dependency PR #4523 merge commit / exact new dev: `4906d0e29c18d137d15c19af11a2bb0864f017ad`
- rebased #4524 exact head: `3baf82e3ac7ce0143b80e51e934ffd128cb7a982`
- ancestry proof: merge-base is exact dev `4906d0e29c18d137d15c19af11a2bb0864f017ad`
- remote updated with force-with-lease; worktree clean

Fresh post-dependency verification:

- exact shard-2 command (unchanged production limits): `bun scripts/run-bun-test-files.ts --root=packages/coding-agent --shard=2/8 --timeout=30000 --file-timeout=300000 --concurrency=1` — **174/174 files passed**
- focused attribution/default-selection/auto-compaction suites — **79 pass, 1 existing skip, 0 fail**
- `bun --cwd=packages/coding-agent run check` — pass

This proves the previously external #4518 login fixture blocker is removed and the complete shard containing the original #4519 regression is green on the exact rebased head. Issue #4522 remains separately active with no PR/landing; no SDK cancellation code was copied or modified here.

Signed: Bellman / issue-4519 owner

— *[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Postmerge dependency update: PR #4523 is now in dev at `4906d0e29c18d137d15c19af11a2bb0864f017ad`. Push Dev CI run 31764983841 confirms shard 3 is green and all login-preset cases pass. Rebase onto this dev commit and rerun; the remaining shard-2 failure is the #4519 attribution cluster owned by #4524.

**Comment by Yeachan-Heo** [comment]
@probepark Independent exact-head review requested for PR #4524 at `3baf82e3ac7ce0143b80e51e934ffd128cb7a982` over exact base `4906d0e29c18d137d15c19af11a2bb0864f017ad`.

Please review the admission-order contract adversarially: prompt-first and selection-first causality, fail-fast same-session reentrancy, inherited continuation admission without holding a lease across `waitForIdle`, successor/cancellation ordering, and deterministic disposal settlement. The exact binary diff digest is `6e56942f84ef6de4fb89e55ecb90439b699faf0ca629a76bbb029200aa587b49`.

Current verification: attribution 11/11; durable selection 45/45; auto-compaction 23 pass + 1 existing skip; SDK host wiring 104/104 in isolation; exact shard 2 174/174 files; coding-agent check/types pass. Please submit an authenticated GitHub APPROVED or CHANGES_REQUESTED review bound to this exact head.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Review by probepark — APPROVED** [review]
## Approve - this closes the #4519 red I reported a few hours ago, proven both ways

Reviewed `3baf82e3ac7ce0143b80e51e934ffd128cb7a982` against base `4906d0e29`.

### Fail-before / pass-after

I filed the reproduction on #4519 earlier tonight, so I ran the exact same command on both sides:

```
# base 4906d0e29
$ bun test packages/coding-agent/test/agent-session-before-agent-start-attribution.test.ts
(fail) ... > orders an accepted prompt before a later default selection through provider start
(fail) ... > orders an accepted default selection before later prompt preflight
(fail) ... > disposal drains an active selection
 6 pass  3 fail

# head 3baf82e3a
$ bun test <same file>
 11 pass  0 fail
```

All three targeted failures gone, and the suite grew from 9 to 11 tests rather than shrinking -
the fix came with coverage instead of replacing assertions. Related suites are clean too:

```
$ bun test .../agent-session-default-model-selection.test.ts \
           .../agent-session-auto-compaction-continue.test.ts \
           .../agent-session-midrun-compaction.test.ts
 87 pass  0 fail

$ bun --cwd=packages/coding-agent run check    -> exit 0   (biome + tsc --noEmit, 2837 files)
```

### The design holds up

`agent-session.ts` reads `+153/-99`, but `git diff -w` puts it at `76/22` - the rest is
reindentation from the new `try`/`finally`. The substance is three things:

1. **A causal selection fence reserved synchronously.** `#selectionFenceTail` is chained
   *before* any `await`, so a later external prompt queues behind an in-flight selection instead
   of racing it. This is the actual root cause - the old code did
   `await this.#modelRegistry.getApiKey(...)` first and yielded before establishing any ordering.
2. **`#sessionAdmissionClosing` split out from `#sessionAdmissionClosed`**, with
   `allowDuringClosing` so an in-flight selection drains during dispose rather than being
   rejected as busy. That is precisely the `disposal drains an active selection` failure -
   previously it hit `#sessionAdmissionBusyError` from `#withSessionAdmission`.
3. **Session-identity guards around the credential probe** (`this.sessionId !== expectedSessionId`
   -> throw, checked on both sides of `getApiKey`), which covers the "must not mutate a successor
   session" bullet in #4519.

Uses `Promise.withResolvers()` per AGENTS.md rather than the `new Promise` idiom.

### The one thing I went digging on

`#closeSessionAdmission` flips queued waiters from `ready.reject(busy)` to `ready.resolve()`,
which looks at first glance like it lets queued work run after close. It does not:

```ts
// #closeSessionAdmission - closed is set BEFORE the queue is drained
this.#sessionAdmissionClosed = true;
for (const entry of queued) { entry.released = true; entry.ready.resolve(); entry.settled.resolve(); }

// #withSessionAdmission - immediately re-checked after the await
await awaitPromptInvocationPreflight(entry.ready.promise, signal);
if (this.#sessionAdmissionClosed || ((this.#sessionAdmissionClosing || this.#isDisposed) && options?.allowDuringClosing !== true)) {
  entry.released = true; entry.settled.resolve(); ...; throw this.#sessionAdmissionBusyError();
}
```

Every queued waiter still throws busy - the rejection just moved to the post-await check, which
additionally settles the entry and activates the next one. Strictly cleaner than rejecting the
`ready` promise, and the `disposal drains an active selection` test covers it.

---

### The verdict line is malformed and could never have validated

```
gajae.pr-review-verdict.v1 needs-human sha256:6e56942f... reviewer:probepark evidence:...
```

The grammar is `reviewer:(architect|critic|human) reviewer-id:<id>`. This line has
`reviewer:probepark` with no `reviewer-id:` field at all, so the gate rejects it at
`Malformed gajae.pr-review-verdict.v1 line.` before it ever evaluates the verdict - the
`needs-human` never even gets read.

Worth watching across the queue: I have now seen three distinct malformed/unbacked verdict
lines tonight (#4532 named a subagent id as the reviewer, #4526 asserted an approval from me
that did not exist, this one drops a required field). The line is a signed statement, not
boilerplate - if it is being generated, the generator needs to validate against the same regex
CI uses.

I have corrected it to `reviewer:human reviewer-id:probepark` with the digest I computed
independently: `6e56942f84ef6de4fb89e55ecb90439b699faf0ca629a76bbb029200aa587b49`, matching the
declared value exactly.

### Verdict

**merge-approved.** Right root cause, real coverage, no assertion laundering. Please land this
soon - shard-2 is red across the whole open queue because of #4519, so this unblocks more than
itself.

<sub>Reviewed by @probepark - method: base-vs-head runs of the exact failing suite in a detached worktree with real `bun install` and rebuilt natives, related-suite regression run, whitespace-normalized diff to isolate the 76/22 substantive change, manual trace of the close-path resolve/reject flip against the post-await guard, package typecheck, independent digest recomputation.</sub>

**Comment by Yeachan-Heo** [comment]
CI classification and exact-head approval evidence:

- review-event run `31765944256` was not an authoritative normal pull-request validation. Native-build job `94662009722` was cancelled by workflow concurrency at 03:19:49; no product test failed.
- evidence producer job `94663334206` then failed closed because its required native-build evidence was cancelled. Aggregate job `94663359597` was derivative.
- exact head/base remain `3baf82e3ac7ce0143b80e51e934ffd128cb7a982` / `4906d0e29c18d137d15c19af11a2bb0864f017ad`, diff digest `6e56942f84ef6de4fb89e55ecb90439b699faf0ca629a76bbb029200aa587b49`.
- independent collaborator **probepark** submitted authenticated exact-head APPROVED review `4933522086`: https://github.com/Yeachan-Heo/gajae-code/pull/4524#pullrequestreview-4933522086
- the PR body now contains exactly one canonical `merge-approved` verdict line bound to that reviewer, exact digest, and approval evidence. This body edit triggers a fresh normal `pull_request` validation run.
- a local shard-2 replay observed one isolated `sdk-mcp-discovery.test.ts` process failure after prior broad execution; the exact file immediately passed 42/42 in isolation, while the authoritative prior exact shard replay passed 174/174. No timeout, retry masking, or product change was made.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
PR contract formatting fix and authoritative validation receipt:

- superseded normal pull-request run `31767122010`, bootstrap job `94665277035`, failed only because the verdict line used `reviewer:probepark` and omitted the required reviewer class plus `reviewer-id`; no source or product test failure was involved.
- PR body now has exactly one line matching the default-branch schema:
  `gajae.pr-review-verdict.v1 merge-approved sha256:6e56942f84ef6de4fb89e55ecb90439b699faf0ca629a76bbb029200aa587b49 reviewer:human reviewer-id:probepark evidence:https://github.com/Yeachan-Heo/gajae-code/pull/4524#pullrequestreview-4933522086`
- fresh authoritative normal `pull_request` run `31767310776` started at the unchanged exact head `3baf82e3ac7ce0143b80e51e934ffd128cb7a982`.
- its PR contract bootstrap job `94665810066` is terminal **success**.
- native-build job `94665886595` is currently running; primitive jobs and aggregate are being monitored to terminal completion.
- review-event run `31766792364` remains superseded; its evidence-producer failure derived from concurrency cancellation of native-build and is not a product failure.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Dependency handoff for external maintainer PR #4512: exact head `3baf82e3ac7ce0143b80e51e934ffd128cb7a982` now has authenticated exact-head approval and terminal full Dev CI run `31767310776` with 19 success, 5 skipped, and no bad jobs. The visible PR rollup remains `UNSTABLE` only because it retains superseded failed/cancelled runs; the authoritative latest-head run is green. Please validate the canonical merge receipt and merge #4524 to `dev` under this lane's authority. #4512 is waiting only on this landing and separately owned #4522.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*
