### PR TITLE
fix(retry): bound ollama-cloud first-event timeout retries (#713)

### LINKED ISSUE #713: Bug: ollama-cloud provider first-event timeout triggers retry failure and usage spikes
Discord report from gajae community (`#gajae-code`) says switching provider to `ollama-cloud` can crash sessions with:

- `Error: Provider stream timed out while waiting for the first event`
- `Error: Retry failed after 1 attempts: Retry continuation failed to start`

Reporter also observed sudden usage spikes after the retry/continuation path.

Initial maintainer hypothesis: provider first-event timeout + retry continuation may be charging or attempting recovery in a way that is not bounded/visible enough for this provider route.

Need to verify with sanitized reproduction:

- gajae-code version / commit
- provider profile shape, with keys removed
- whether streaming is enabled for the provider route
- minimal prompt that triggers the first-event timeout
- whether usage spike comes from retry attempts, continuation setup, or provider-side billing counters

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### PR DESCRIPTION
**Pull request by Yeachan-Heo**
## Summary

Fixes #713: `ollama-cloud/kimi-k2.7-code` (and other ollama-cloud models) could hit `Provider stream timed out while waiting for the first event` even for tiny prompts, and with retries enabled the continuation retry looped and spiked usage. Disabling retries was the only workaround.

## Root cause

The first-event watchdog message matched the generic transient classifier in `AgentSession#classifyErrorForRetry` (`/timed? out|timeout/`), and the `transient` class is **unbounded** by design (retry forever, delay-capped only, with `unbounded: true` observability). For ollama-cloud — a remote, queued, billable backend that can stall before its first token — every unbounded continuation re-issued the full request, so the loop silently spiked upstream usage. With retries off, the spike stopped, confirming the retry path as the cause.

There is no provider-internal retry for the ollama-chat path (the lazy-stream wrapper forwards without retrying), so the agent-session classifier is the only and correct place to fix this.

## Fix (narrow, fail-closed)

- New `first_event_timeout` retry classification that is **retryable but bounded** by `retry.maxRetries` (it is intentionally excluded from `unboundedClass`).
- Scoped to the **ollama-chat API**, which is exclusively `ollama-cloud` (local Ollama uses the `openai-responses` API). First-party providers keep their existing unbounded first-event-timeout retry behavior — verified by a scope-guard test.
- No new user-facing config: the bound reuses the existing `retry.maxRetries` budget.

## Tests

`packages/coding-agent/test/agent-session-resilient-retry.test.ts`:
- bounds ollama-cloud first-event timeouts to `retry.maxRetries` then surfaces (proves no unbounded loop / usage spike);
- first-party (Anthropic) first-event timeouts stay unbounded (scope guard).

## Verification

- `bun test` (coding-agent) retry suites: resilient-retry + retry-fallback **31 pass**, retry-cap **3 pass**; ai anthropic-retry + openai-first-event-timeout **18 pass**.
- `bun run check:types` (coding-agent, tsgo) clean; biome clean on changed files.

Validation scoped to the affected package (the change is isolated to `packages/coding-agent`); a full-repo `check:ts`/test run was not required for a single-package classifier change.

Base: `dev`.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### CODE REVIEW

**Review by Yeachan-Heo — COMMENTED** [review]
## Red-team merge gate review — PR #723 (fix #713: bound ollama-cloud first-event timeout retries)

**Terminal verdict: `BLOCKED_CI_PENDING`**

Code review is clean — **no changes required**. The gate is held only because the repo's required CI checks have not concluded. Re-evaluate when CI is green.

---

### What the change does
- Adds a new retry class `first_event_timeout` that is **retryable but bounded** by `retry.maxRetries` (excluded from `unboundedClass`), instead of joining the unbounded `transient` class.
- Scoped via `#shouldFailClosedOnFirstEventTimeout` to the **ollama-chat API only** (`this.model?.api === "ollama-chat" || message.api === "ollama-chat"`).
- Classifier ordering routes the timeout to `first_event_timeout` **before** the generic transient check (`agent-session.ts:7926-7934`).

### Verification (static, against `dev`)
- **Classification wiring is consistent.** Both retry entry points (`#isRetryableError` and `#handleRetryableError`) use `#classifyErrorForRetry`. `first_event_timeout` is included in `#isRetryableError` (retry is attempted) and excluded from `unboundedClass` at `agent-session.ts:8207`, so the bounded path at `:8220` (`!unboundedClass && #retryAttempt > maxRetries`) surfaces after the budget — proving no unbounded loop / usage spike.
- **Scope claim holds.** `ollama-chat` is exclusively `ollama-cloud`: `models.json` declares every ollama-cloud model with `"api": "ollama-chat"`, and `ollamaCloudModelManagerOptions` returns `ModelManagerOptions<"ollama-chat">`. Local Ollama (`ollama` provider) uses `openai-responses` (`ollamaModelManagerOptions`). So first-party providers (Anthropic/OpenAI/local Ollama) keep their existing unbounded first-event-timeout behavior.
- **Regex matches the real message.** `streamOllama` is wrapped by `createLazyStream` (`register-builtins.ts:409`); on first-event timeout the wrapper emits `"Provider stream timed out while waiting for the first event"` (`:161`) with `api: model.api === "ollama-chat"`. The classifier regex matches both the shared message and per-provider variants.
- **Fallback intact.** Model/credential fallback still runs for the bounded class; once fallback switches off ollama-cloud, subsequent first-event timeouts are reclassified against the new provider's API (unbounded again), which is the desired behavior.

### Local test evidence (this reviewer ran)
- `agent-session-resilient-retry.test.ts`: **19 pass / 0 fail**; the two #713 tests pass (`-t 713` → 2 pass). Bounded test asserts `1 + maxRetries` requests and `unbounded === false`; scope-guard test asserts first-party stays `unbounded === true` and recovers.
- `agent-session-retry-fallback.test.ts` + `agent-session-retry-cap.test.ts`: **15 pass / 0 fail** (fallback 12 + cap 3 — matches the PR's stated counts; resilient-retry 19 + fallback 12 = 31).
- `bun run check:types` (coding-agent, tsgo): **clean (exit 0)**.

### Non-blocking notes
1. A user-defined model that declares `api: "ollama-chat"` against a non-ollama-cloud endpoint would also be bounded. This is the fail-closed (safe) direction and consistent with the design that treats `ollama-chat` == ollama-cloud.
2. `#retryAttempt` is shared across classes, so a first-event timeout following a long unbounded `transient` run can surface before a fresh `maxRetries` budget. Pre-existing behavior shared with `usage_limit`; fail-closed and not introduced here.
3. The auto-compaction retry loop (`agent-session.ts:7613-7618`) still treats first-event timeouts as transient via `#isTransientErrorMessage`, but is bounded by `attempt < maxRetries` there, so no unbounded loop.

### Why BLOCKED_CI_PENDING
At review time `mergeStateStatus: UNSTABLE` with required Dev CI checks still `IN_PROGRESS`:
- `gjc-state-gates` — pending
- `Affected path validation` — pending

No code defect blocks this PR; the merge gate cannot certify readiness until those checks complete green. Do not merge.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
## CI triage — `BLOCKED_NON_ATTRIBUTABLE`

**Failing check:** `Affected path validation` (Dev CI, `.github/workflows/dev-ci.yml`)
- Run [`27563941498`](https://github.com/Yeachan-Heo/gajae-code/actions/runs/27563941498), job [`81482843516`](https://github.com/Yeachan-Heo/gajae-code/actions/runs/27563941498/job/81482843516)
- Head: `2c1db0527bca0a6e3af5cd751090c23cbf387b09` · Base: `dev` (BASE_SHA `9153fc503ed10ff2b0ac2c70301ee079c1a4e2b5`)
- Failing step #12 `Run affected path checks and tests` → group `Check @gajae-code/coding-agent` → command `biome check . && bun run check:types` exited `1`.

**Root cause (from CI log metadata):** a single Biome `format` error:

```
packages/coding-agent/test/bridge/bridge-endpoints-parse.test.ts:11
  × Formatter would have printed the following content:
   11 │ - it("enables all matrix keys for \"all\" (case-insensitive)", () => {
   11 │ + it('enables all matrix keys for "all" (case-insensitive)', () => {
Checked 1633 files in 552ms. No fixes applied. Found 1 error.
```

Biome wants the double-quoted string (which escapes inner `\"`) rewritten with single quotes.

**Why this is not attributable to this PR:**
- PR #723 changes exactly 3 files, none being the offending file:
  - `packages/coding-agent/CHANGELOG.md`
  - `packages/coding-agent/src/session/agent-session.ts`
  - `packages/coding-agent/test/agent-session-resilient-retry.test.ts`
- `packages/coding-agent/test/bridge/bridge-endpoints-parse.test.ts` **does not exist in this PR's head** (`2c1db05`); it lives only in base.
- The offending line was introduced into `dev` by commit `9153fc50` (#663, *"feat(bridge): opt-in GJC_BRIDGE_ENDPOINTS env…"*) and is still present at current `origin/dev` HEAD (`009d11c`).
- `biome check .` scans the whole `@gajae-code/coding-agent` package, so editing `agent-session.ts` made the package "affected" and surfaced this pre-existing **base-only** formatting defect against the merge ref.

**Disposition:** This is a base (`dev`) formatting defect, not introduced or modified by PR #723. It cannot be fixed within this PR's scope without pulling in an unrelated base change. The fix belongs in `dev` (run `biome check . --write` on `packages/coding-agent/test/bridge/bridge-endpoints-parse.test.ts`). The `gjc-state-gates` check on this PR is green.

Verdict: **`BLOCKED_NON_ATTRIBUTABLE`**

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Heads-up: the `test/bridge/bridge-endpoints-parse.test.ts` Biome **format** error that failed Affected-path validation on this PR's merge ref originates from dev/base, not from this branch. Fixed narrowly in #726 (single-quote the outer `it(...)` description; formatting-only, no logic). Once #726 lands on `dev`, re-running CI here (or rebasing on updated `dev`) should clear that blocker.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Refresh pushed after #727 landed on `dev`.

Validation before push:
- `bunx biome check .` in `packages/coding-agent` → pass (`1640 files`, no fixes)
- native addon build → pass (`bun --cwd=packages/natives run build`)
- targeted retry suite after native build → pass (`packages/coding-agent/test/agent-session-resilient-retry.test.ts`: 19 pass, 0 fail)
- `bun run check:types` in `packages/coding-agent` → pass

I intentionally restored `packages/coding-agent/src/internal-urls/docs-index.generated.ts` before pushing; that file was dirtied by local docs-index generation during validation and is unrelated to #723's retry fix.

CI should rerun on the refreshed PR branch now.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
## CI triage: PR #723 — verdict `BLOCKED_BASELINE_OR_CI_SHARED`

**Failed run/job:** [`Affected path validation`](https://github.com/Yeachan-Heo/gajae-code/actions/runs/27570002803) — run `27570002803`, job `81503732072` (head `147fe9f2`). `gjc-state-gates` passed.

### TL;DR
The 20 failing tests are a pre-existing lifecycle/timer/subprocess-cleanup cluster on `dev`. They are **not** caused by this PR. #723's diff is confined to retry classification in `agent-session.ts` and touches none of the failing paths. The failures reproduce identically on a clean `origin/dev` checkout in the same environment.

### 1. This PR's diff cannot reach the failing tests
`git diff origin/dev...HEAD` changes only **3 files**:
- `packages/coding-agent/CHANGELOG.md`
- `packages/coding-agent/src/session/agent-session.ts` — adds a `first_event_timeout` retry class (private methods `#isFirstEventTimeoutErrorMessage` / `#shouldFailClosedOnFirstEventTimeout`); no exported API change.
- `packages/coding-agent/test/agent-session-resilient-retry.test.ts`

Every failing test file is **byte-identical to `origin/dev`** (`git diff origin/dev...HEAD -- <file>` → 0 lines):

| Failing cluster | File | Diff vs dev |
|---|---|---|
| ExtensionUiController hook editor abort (3) | `src/modes/controllers/extension-ui-controller.ts` + `test/hook-editor.test.ts` | 0 lines |
| executeBash abort/timeout cleanup + huge output (3+1) | `test/bash-executor.test.ts` | 0 lines |
| LSP lifecycle (1) | `test/lsp/lsp-lifecycle.test.ts` | 0 lines |
| MCP transport lifecycle redteam (3) | `test/runtime-mcp/transport-lifecycle.redteam.test.ts` | 0 lines |
| MCP manager lifecycle cleanup (7) | `test/runtime-mcp/manager-lifecycle.test.ts`, `test/mcp-lifecycle-cleanup.test.ts` | 0 lines |
| DAP lifecycle socket cleanup (2) | `test/dap/dap-lifecycle.test.ts` | 0 lines |

### 2. Failures reproduce identically on `origin/dev` (same machine/env)
Ran the deterministic reproducers on this branch (`147fe9f2`) and on a clean `origin/dev` worktree (`1f4bc254`, the merge-base):

| Test | This PR branch | `origin/dev` baseline |
|---|---|---|
| `bash-executor.test.ts` | 3 fail (lines 228, 305, 420) | 3 fail (lines 228, 305, 420) |
| `hook-editor.test.ts` | 3 fail (lines 685, 817) | 3 fail (lines 685, 817) |
| `lsp/lsp-lifecycle.test.ts` | 3 pass | 3 pass |

- `bash-executor` 228/305 surface `"timeout"` instead of `"result"` (subprocess-cleanup timing under load); 420 is the multi-million-line output test returning `totalLines 1187465 < 5000000` (resource pressure).
- `hook-editor` 685/817 fail with `TypeError: this.ctx.editorContainer.detachChild is not a function` — a stale test mock on `dev`, present regardless of this PR.
- `lsp-lifecycle` passes locally on both; the CI failure was an environment artifact: `Cannot find module '/tmp/packages/coding-agent/src/lsp/lspmux.ts'` (probe spawned in a `/tmp` dir couldn't resolve the source module path on the runner).

### 3. PR #723's own change is green
`bun test packages/coding-agent/test/agent-session-resilient-retry.test.ts` → **19 pass, 0 fail**, including the new `bounds ollama-cloud first-event timeout retries` case.

### 4. Cross-PR corroboration
The identical 20-test cluster appears on PR #728 (an unrelated diff) in the same window, confirming the failures are branch-independent / CI-environment shared.

### Verdict
`BLOCKED_BASELINE_OR_CI_SHARED` — no code change applied to #723. The failures belong to a shared `dev`/CI-environment lifecycle-cleanup cluster, not to this PR. Recommend tracking/fixing the cluster on `dev` (the `bash-executor` resource/timing tests, the `hook-editor` `detachChild` mock, and the `lspmux` `/tmp` probe path), then re-running CI on this branch.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
## CI triage: `Affected path validation` failure is a shared baseline cluster, not introduced by this PR

**Terminal verdict: `BLOCKED_BASELINE_OR_CI_SHARED`** — no code change made.

### Failing run
- This PR: run [`27570002803`](https://github.com/Yeachan-Heo/gajae-code/actions/runs/27570002803) / job `81503732072` (`Affected path validation`), `conclusion: failure`, `headSha: 147fe9f2` (== current PR head).
- Result: `6152 pass / 358 skip / 20 fail`.

### Why these failures are unrelated to #723
This PR's diff vs `origin/dev` (merge-base `1f4bc254`) touches **only 3 files**:
- `packages/coding-agent/src/session/agent-session.ts` (retry classifier: adds a `first_event_timeout` class, gated on the `ollama-chat` API + a first-event-timeout message regex)
- `packages/coding-agent/test/agent-session-resilient-retry.test.ts` (2 new retry tests)
- `packages/coding-agent/CHANGELOG.md`

The 20 failing tests live entirely in unrelated subsystems — MCP transport/manager lifecycle, LSP `lspmux`, DAP adapter, `bash-executor`, and the hook editor:

```
ExtensionUiController hook editor abort > (3 tests)
executeBash > native abort/timeout cleanup + multi-million-line output (3 tests)
LSP lifecycle behavior > lspmux status probe clears its timeout and reaps the probe process when status hangs
MCP transport lifecycle red-team regressions > (3 tests)
MCP manager lifecycle cleanup > (7 tests)
DAP lifecycle behavior > socket-mode startup timeout / unix .sock unlink (2 tests)
bash resource lifecycle red-team > caps huge bash artifacts with truncation metadata
```

`git diff <merge-base>..HEAD` against every one of those test files **and** their source modules (`src/lsp/lspmux.ts`, `src/runtime-mcp/*`, `src/tools/bash-executor.ts`, `src/modes/controllers/extension-ui-controller.ts`) is **empty**. The retry-classification change has no code path into MCP/LSP/DAP/bash/hook lifecycle.

### Cross-PR proof (shared baseline)
The **identical 20-test cluster** fails on an unrelated PR — #728 (`fix(agent): tear down browser/Python subprocesses on signal exit (#698)`), run [`27569551533`](https://github.com/Yeachan-Heo/gajae-code/actions/runs/27569551533) / job `81502188389`: same `20 fail`, same test names. Two disjoint diffs producing the same failure set ⇒ the cluster is shared CI baseline, not caused by either change.

### Local evidence (on `147fe9f2`, this exact commit)
- This PR's own tests: `bun test test/agent-session-resilient-retry.test.ts` → **19 pass / 0 fail** (incl. the new bounded/unbounded ollama-cloud first-event-timeout cases).
- `bun test test/runtime-mcp/manager-lifecycle.test.ts` → **7 pass / 0 fail** locally (CI-environment/timing sensitive).
- `bun test test/lsp/lsp-lifecycle.test.ts` → fails locally too, with a **test-harness path bug** independent of this PR: it probes a doubled path `.../packages/coding-agent/packages/coding-agent/src/lsp/lspmux.ts` (`Cannot find module`).

### Notes
- This PR already has the latest `origin/dev` merged in (`147fe9f2` is a `Merge origin/dev` commit), and the cluster persists — so it is not resolved by current `dev` either.
- Recommend treating the `Affected path validation` lifecycle/timer/subprocess cluster as a baseline CI fix tracked separately; #723 should not be blocked on it.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Affected-path rerun still fails on the same shared lifecycle/timer cleanup cluster.

Evidence:
- Original failed run/job: `27570002803` / `81503732072`
- Rerun failed job: `81517554009`
- `gjc-state-gates`: success
- The rerun still reports the same 20 failures across hook editor abort, bash native cleanup/huge output, LSP lifecycle, MCP transport/manager lifecycle, DAP socket cleanup, and bash resource lifecycle.
- This exact 20-test cluster is also failing on #728's affected-path rerun.
- #723's diff is limited to retry/ollama first-event timeout code and its targeted retry test (`CHANGELOG.md`, `src/session/agent-session.ts`, `test/agent-session-resilient-retry.test.ts`), so these hook/bash/LSP/MCP/DAP cleanup failures are not plausibly caused by #723's retry change.
- Local targeted check also reproduced the bash quarantine failure on this branch; after fixing workspace install/native resolution, the same targeted failure reproduced on `origin/dev`, indicating a shared baseline/environment blocker rather than a #723-specific regression.

Terminal verdict: `BLOCKED_BASELINE_OR_CI_SHARED`. I am holding merge until the shared cleanup-test blocker is resolved or the CI signal is made actionable for this PR.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

**Comment by Yeachan-Heo** [comment]
Review verdict: MERGE_READY.\n\nEvidence checked:\n- Branch updated against current dev.\n- GitHub Dev CI is green: pending 0, blocking failures 0.\n- Merge state is CLEAN.\n- Scoped change remains within the PR intent.\n\nNote: formal approval is not available with current owner-resolved auth for owner-authored PRs, so this signed maintainer comment is the attached review evidence.\n\n—\n*[repo owner's gaebal-gajae (clawdbot) 🦞]*
