### ISSUE TITLE
[Windows] Bound AVX2 PowerShell fallback timeout in required gate

### ISSUE THREAD

**Issue by Yeachan-Heo** [Yeachan-Heo/gajae-code#4781]
## Summary

The required Windows job fails on the current `dev` tree and on PR #4772 head `1750770d7b682dd4aa19da94b65604573b2141e0`, in the live PowerShell 5.1 fallback test for the AVX2 probe. This is outside PR #4772's trusted-home/NSS delta and blocks merge until the owning Windows/native lane fixes and reruns the gate.

## Exact evidence

- PR head: `1750770d7b682dd4aa19da94b65604573b2141e0`
- Current dev base: `a34cbd700b56b9c663daef700e5edd14cbd20470`
- Failed job: [Windows dev:doctor + session-path regression](https://github.com/Yeachan-Heo/gajae-code/actions/runs/32412496468/job/96566096394)
- Runner: Windows Server 2025, image `windows-2025-vs2026` version `20260818.207.1`
- Test command: `bun test ./packages/natives/test/windows-avx2-probe.windows.test.ts`

The preceding live tests passed:

```text
(pass) ... in-process kernel32 probe returns a decisive boolean ... [2.21ms]
(pass) ... default detection chain spawns no subprocess ... [0.78ms]
```

The forced fallback then failed:

```text
(fail) windows AVX2 probe live execution (#4652) > PowerShell 5.1-compatible fallback P/Invoke works when invoked on a real Windows host [5029.78ms]
  ^ this test timed out after 5000ms.
killed 1 dangling process

2 pass
1 fail
Ran 3 tests across 1 file. [5.09s]
##[error]Process completed with exit code 1.
```

No assertion mismatch, PowerShell stdout, or PowerShell stderr was emitted before the synchronous fallback hung; the runner killed the dangling process at the Bun 5-second test deadline.

## Diagnosis

`packages/natives/native/loader-state.js` still calls `childProcess.spawnSync("powershell.exe", ..., { windowsHide: true })` without a timeout. The test forces `detectWin32Avx2Support(() => undefined)`, so it exercises that fallback directly. The failure is therefore a recurring Windows PowerShell/native-probe timeout/environment failure in the repository gate, not a trusted-home change in PR #4772.

PR #4772 has no diff in the AVX2 loader, live test, or Windows CI path relative to `dev`. PR #4780 is the unrelated `errno_name` Windows test-compilation fix; it does not implement the AVX2 probe fix.

## Ownership

Please take this in the Windows/native AVX2 lane associated with closed #4652/#4654. The fix must preserve hidden subprocess behavior, remain compatible with stock Windows PowerShell 5.1, bound or otherwise prevent a wedged fallback from exceeding the test/runtime budget, and rerun the required Windows gate with full stdout/stderr evidence.

Until that owning fix is merged and the exact PR head is rerun green, #4772 must not merge.

**Comment by Yeachan-Heo** [comment]
Comparison complete. A pristine current-dev run checked out `a34cbd700b56b9c663daef700e5edd14cbd20470` and passed the identical Windows job/test: [run 32413903167](https://github.com/Yeachan-Heo/gajae-code/actions/runs/32413903167/job/96570684398), AVX2 fallback `3 pass`, fallback duration `2815.53ms`. It ran on image `win25-vs2026/20260810.198`.

The PR failure ran the identical source/test on image `win25-vs2026/20260818.207`: fallback hung past Bun’s 5000ms test deadline, the runner killed one dangling process, and no assertion/stdout/stderr was emitted. The relevant loader/test/CI files are byte-identical between `a34cbd7` and `1750770d`; this is a Windows runner/PowerShell timing flake, not a PR-only HOME/NSS effect. The unbounded `spawnSync` fallback remains a hardening concern for this owning lane, so the required PR gate must still be rerun green before merge.

**Comment by Yeachan-Heo** [comment]
Second unchanged-head rerun reproduced the same timeout on a different Windows runner (`GitHub Actions 1000412249`): [job 96573338334](https://github.com/Yeachan-Heo/gajae-code/actions/runs/32414712250/job/96573338334), `2 pass`, fallback `5017.14ms`, one dangling process killed, no assertion/stdout/stderr. This confirms a recurring runner/PowerShell timing failure while pristine dev also passed on another image. The same dispatch had a separate affected-native-build failure where Node reported `Argument list too long`; that is runner infrastructure and unrelated to the AVX2 test. PR #4772 remains blocked until the owning lane hardens or quarantines the fallback and the required Windows gate is green.

**Comment by Yeachan-Heo** [comment]
Repeat evidence from unchanged PR #4772 head:

- Required Windows job: https://github.com/Yeachan-Heo/gajae-code/actions/runs/32414712250/job/96573338334
- Job id: `96573338334`
- The first two AVX2 live tests passed; the forced stock PowerShell 5.1 fallback hung past Bun’s 5,000 ms deadline.
- Bun killed one dangling process and the test failed at `5,017 ms`.
- The Windows native build job passed separately.

This is repeatable on the newer runner image, not a one-off. #4781 owns the production timeout/kill fix; #4772 must rebase onto the merged fix and regenerate its digest/review rather than rerun its unchanged head.

**Comment by Yeachan-Heo** [comment]
Issue handoff for owner lane `project-pr-4783-current`:

- Fix implementation is committed as `4a8785ca00dd6e305e539989de6e401cc9345a86` on PR #4783, based on dev `343067ab8f9ab75f427e275f411ca1ed57814ea0`.
- Exact PR diff digest: `51947d01bf77add1f544665bfd9feba56bb935f47a9810dcdcf322e50664d8f9`.
- Reproduction evidence: unchanged PR #4772 failed Windows job `96573338334` at 5,017 ms after Bun killed one dangling PowerShell process: https://github.com/Yeachan-Heo/gajae-code/actions/runs/32414712250/job/96573338334.
- Local evidence: AVX2/host-detect tests 18 pass; natives suite 148 pass, 55 skip; natives package check and tooling check pass.
- Windows evidence already observed on the fix head: `windows-dev-doctor` job `96578878374` passed and the required AVX2 live test job `96580478447` passed.

The PR owner lane owns remaining merge, dev dogfood, and issue closure. This issue lane is held for closure observation only: no further branch push, PR/body edit, CI rerun, review, merge, or other remote mutation is authorized here.

Signed-off-by: Yeachan-Heo

**Comment by Yeachan-Heo** [comment]
Resolved by merged PR #4783 (merge commit ba7096f72184929070f295019e8173c41ab1e468) on dev. Exact head 4a8785ca00dd6e305e539989de6e401cc9345a86 was contract-validated with digest 51947d01bf77add1f544665bfd9feba56bb935f47a9810dcdcf322e50664d8f9. The merged implementation bounds both Windows PowerShell fallback paths to 4,000 ms with SIGKILL, windowsHide, a 4 KiB output cap, safe baseline fallback, shape-only diagnostics, and deterministic timeout/spawn/nonzero/non-decisive tests. Windows live probe CI passed: https://github.com/Yeachan-Heo/gajae-code/actions/runs/32416500005/job/96580478447. The post-merge canonical dev tree was fast-forwarded locally to ba7096f72184929070f295019e8173c41ab1e468 and `bun install --frozen-lockfile && bun run build` passed.
