### PR TITLE
fix(test): complete isUnattended → supportsRemoteGateAnswers rename in test mocks

### PR DESCRIPTION
**Pull request by Yeachan-Heo**
## Summary
- #2521 renamed `WorkflowGateEmitter.isUnattended` → `supportsRemoteGateAnswers`, but its older merge-base missed eight emitter mocks that landed on dev via #2908 (ask.test.ts ×5, sdk-workflow-gate-emitter.test.ts ×2, sdk-host-wiring.test.ts ×1).
- Post-merge dev (4b9d8c8e) broke: `check:types` TS2353/TS2352 errors, shard-8 four AskTool runtime failures (`supportsRemoteGateAnswers is not a function`), shard-6 legacy-emitter waitFor timeout.

## Verification
- `bun run check:types` clean; zero `isUnattended` leftovers repo-wide.
- All five originally failing tests pass individually: 4× AskTool shard-8 tests + shard-6 `workflow gate recommendation projection` (2.0s).
- sdk-workflow-gate-emitter restoration timeouts reproduce identically on pre-#2521 dev (38571d19) — classified pre-existing infrastructure flakiness, out of scope.

Restore-dev-green exception lane.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*

### CODE REVIEW

**Comment by Yeachan-Heo** [comment]
**MERGE_READY** — exact-head review at \`a80b0b27bd62de00faa74663016c884f5626179f\` against current \`dev\` (4b9d8c8e).

Independent adversarial review (fresh critic lane) plus local verification:

- **Completeness**: zero \`isUnattended\` references remain across packages/, python/, crates/, docs/, schemas/, scripts/ — including string-literal, bracket-access, and snake-case variants. (INFO only: inert historical QA prose under \`artifacts/\` still names the old identifier; not runtime-consumed.)
- **Semantic equivalence**: all eight renamed mocks retain the original \`() => true\` capability, matching \`WorkflowGateEmitter.supportsRemoteGateAnswers\` (workflow-gate-broker.ts:98) and the broker's always-true implementation.
- **Failure coverage**: \`check:types\` clean; all five originally failing tests pass individually (4× AskTool shard-8 + shard-6 \`workflow gate recommendation projection\`, 2.0s). The sdk-workflow-gate-emitter restoration timeouts reproduce identically on pre-#2521 dev (38571d19) — pre-existing infrastructure flakiness, not attributable to this diff or #2521.
- Exact-head CI: 21 checks, all terminal green; mergeable/clean.

Merging as the restore-dev-green exception.

—
*[repo owner's gaebal-gajae (clawdbot) 🦞]*
